trailofbits/manticore

docs/conf.py

Readthedoc was unable to build our docs because we check for z3 on the machine and fail if its not there. Using the officially supported mocking mechanism `autodoc_mock_imports` doesn't work because that doesn't handle submodules well, and in addition to mocking the specified submode (in our case `manticore.core.smtlib.solver`), mocks modules higher in the hierarchy also.
You can see docs built from this branch at http://manticore.readthedocs.io/en/dev-rtd-mock/api.html#helpers

Add read the docs mock

---

manticore/__main__.py
manticore/core/cpu/abstractcpu.py
manticore/manticore.py

This PR also sets the default `--verbose` verbosity to 4, which is in my opinion much more sane

Only make registers appear on verbosity level 5

---

manticore/models/linux.py

The [musl](https://www.musl-libc.org/) dynamic loader relies on this value and thus crashes if it is incorrect.

Use correct value for AT_PHENT

---

manticore/models/linux.py

i386 and amd64 had their register sets reversed. This fixes that.

Fix incorrect syscall arg regs for X86 (#224)

---

CHANGELOG.md
manticore/core/executor.py
manticore/core/state.py
tests/test_state.py

Fixes #195 
This includes `state.constrain` as an official, documented API. This also adds a CHANGELOG.md to create a single place users can learn about important changes. It essentially copies http://keepachangelog.com/en/0.3.0/

Formalize API for constraining a State

---

manticore/core/memory.py
tests/test_memory.py

When verifying Manticore's emulation integrity, it is beneficial to run a binary in lock-step with a native or qemu-emulated execution. This works well for general instruction semantics, but fails when emulating system calls. Manticore's state might not exactly match that of the reference implementation.
We would like to be able to capture all of Manticore's memory writes between invoking a system call and its return, to mimic them precisely in the emulated instance.
This implementation lets calling code start and stop memory tracing. Stopping a memory trace returns a list of all write actions that occurred since it begun. Start/stop pairs can also be nested, if a future implementation requires it.

Add memory tracing

---

manticore/core/state.py

This reduces the symbolic data that could be introduced into the program by only making symbolic bytes that correspond to the wildcard character. Previously, even non wildcard bytes would be symbolic `ArraySelect`s due to the `symb[i]`.

Refactor symbolicate_buffer

---

manticore/manticore.py

This very strictly constrains the arg/env to the length of the symbolic
string which is too strict for many use cases.
For example:
manticore ./bin +++++
that symbolic string would only be allowed to be strings of length 5,
and no shorter.

Don't use string=True for symbolic arg/env

---

.travis.yml
README.md
setup.py

3.0.4, the default as-is is from 2015 and has a slightly broken installer, necessitating the use of --no-binary

Use newer, less broken capstone version

---

manticore/core/cpu/x86.py

Maticore crashs when it reachs the following instructions:
```
vorpd  ymm8,ymm1,ymm0
vorpd  ymm9,ymm3,ymm2
vorpd  ymm10,ymm5,ymm4
```
Maticore uses a wrong instruction size to increase the PC. 
```
vorpd ymm8, ymm1, ymm0
rol ch, 0x65
push rsi
retf 0x55c5
```
Therefore I added VORPD and VORPS instructions to x86.py

VORPD and VORPS instructions added

---

manticore/core/cpu/abstractcpu.py
manticore/platforms/linux.py
tests/test_linux.py

* Move stack-based helpers to `Cpu`
* Refactor initialization so that we can create a platform model that isn't associated with an ELF file
* Simplify SLinux sys call handling to rely on normal `ConcretizeArgument` exceptions

Linux platform refactoring

---

tests/test_binaries.py

Without this, the manticore subprocess can fail, but the test still passes

Check returncode of manticore integration tests

---

tests/test_manticore.py

Other tests verify that the hook infrastructure is set up, but not that the hook actually runs.

Add real test for m.hook API

---

manticore/core/smtlib/solver.py
manticore/core/smtlib/visitors.py

in `solve.py`: 
* Remove of the incremental mode in `get_all_values()` (two distinct calls to the solver are faster than using incremental mode in the context of `get_all_values()`)
in `visitors.py`:
* Remove duplicated prints in `PrettyPrinter`and `TranslatorSmtLib` (smt formulas are now smaller)
* Fix `visit` in `ArithmeticSimplifier`
* Fix the use of `ConstantFolderSimplifier` (no-trivial operators were not called by `ArithmeticSimplifier`)

Optimizations and bug fixes in smt formulas

---

manticore/platforms/linux.py

signal_transmit can crash if the `fd` passed is not being waited on ( `connections(fd)` does not correspond to an index in `self.rwait`). This PR slightly restructures the code checks that this condition is true.

Fix signal_transmit crash

---

manticore/manticore.py
manticore/platforms/linux.py

Currently, Linux.sys_write assumes `is_full` and `transmit` methods on file descriptor objects, however File has neither of these. Add `is_full` to File, and refactor so both Files and Sockets use `write`

Make Linux write(2) work with Files

---

manticore/platforms/linux.py

Fixes a bug where if a program opens a non-symbolic file, sys_write will crash since Files don't have .sync, only SymbolicFiles

Add .sync to regular Files also

---

manticore/manticore.py

Hack around simple chdir OS model, which actually calls chdir on the host. If a program chdirs and we use relative paths for workspace operations, we will fail all future operations on the workspace.
In the future, we should implement a virtual filesystem ( #296 ) to avoid the need for this.

Use global path for workspace

---

manticore/core/cpu/arm.py
manticore/platforms/linux.py
manticore/utils/emulate.py
tests/test_armv7cpu.py

WIP, soliciting feedback
this branch implements the `mrc`, `movt`, `utxb`, `ldrex`, and `strex` instructions, in an effort to support the binary associated with #182
Still to do:
* implement handling of `lsl.w   r5, r5, #3`  -- it causes an assertion error, as the current implementation of `LSL` assumes the shift amount operand is a register
* implement `ldrd` instruction
* implement `strd` instruction

WIP - Dev add mrc and movt

---

manticore/core/executor.py

When the number of workers is high but the queue is empty, manticore spends a ton of time in _getState doing nothing. Running [this script](https://github.com/trailofbits/manticore-examples/blob/master/google2016_unbreakable/win.py) with 40 processes instead of 10 on my machine takes ~12,000 seconds before this PR and ~300 after.

short circuit _getState when queue is empty

---

manticore/platforms/linux.py

If you run `manticore crackme` you'll get the error `seek() takes exactly 1 argument (2 given)`, this is because the `seek` function in the `Socket` class of `linux.py` is implemented without accepting any parameters. I changed this to match the other seek declarations.

Changed Socket parameters to accept seek paramaters

---

manticore/manticore.py

Currently, at no verbosity level do we activate debug level logging
from the executor, however there is significant debug level logging in the
executor for state forking output.

Activate executor debug logging with verbosity=2

---

manticore/manticore.py
tests/test_binaries.py

#310 accidentally changed the default of Manticore to be much more verbose than just the minimal "Generating testcase" lines. This reverts that and adds Executor debug verbosity only on level 2+.

Fix verbosity=1 

---

manticore/platforms/linux.py

- Add ctypes to lseek for signed seeks. Pass whence to seek. Fixes edge case bug where 64 bit int is too big to fit in Python's long.
- Move mmap and related functions from SLinux to Linux.
- Introduce function _sys_open_get_file to isolate symbolic code in sys_open to SLinux.

Feature changes to support concrete execution.

---

manticore/core/cpu/arm.py
tests/test_armv7cpu.py

Fixes lsl.w in thumb mode and includes a test that exercised the problematic behavior.
The BX instruction now sets the processor mode appropriately for disassembly.

lsl.w in thumb mode fixed, plus tests

---

manticore/models.py
manticore/platforms/decree.py
manticore/platforms/linux.py
manticore/platforms/windows.py

Fixes ConcretizeArgumet misspelling.
Files In Effect:
-manticore\models.py | Line 86 & 88
-manticore\platforms\decree.py | Line 1089, 1093, & 1097
-manticore\platforms\linux.py | Line 2070, 2074, 2078, 2085, 2089, & 2093
-manticore\platforms\windows.py | Line 544, 586, 650, 750, 856, & 864.
Thank you for letting me contribute to your project!
- Signed Ffio1

Fixes ConcretizeArgument Misspelling

---

manticore/utils/event.py

`forward_signals()` iterates through a list of strings returned by `dir(source)`. This has the side-effect of invoking all properties on the source object. If the property has side effects, they will be executed when `getattr()` is called.
Iterating through `source.__dict__` ensures that we only iterate through instance members (which signals should be) and remain side-effect free.

Update forward_signals() behavior

---

manticore/core/executor.py
manticore/core/memory.py
manticore/core/state.py
manticore/platforms/windows.py
tests/test_memory.py

Fixes #359 
Previously, raised `MemoryExceptions` were uncaught and caught output like below, which makes it seem like Manticore crashed.
This pull request
- catches MemoryExceptions and generates a testcase
- refactors StateException/TerminateState to use `*args, **kwargs` less for better readability
- refactors MemoryException and children, slightly changes error message format. opinionated UI change: doesn't add the memory exception address to the `.message` if it is symbolic, as something like `<manticore.core.smtlib.expression.BitVecAnd object at 0x7fb801c36410>` is not very useful output.
- update locations where MemoryExceptions are raised
output:
after:
```
2017-06-30 13:40:10,262: [5192] MANTICORE:INFO: Loading program testt
2017-06-30 13:40:11,150: [5192] MANTICORE:INFO: …
```

Catch and refactor MemoryExceptions

---

manticore/manticore.py

Previously, setting verbosity to something high temporarily and then later lowering it would not be effective.

Fix lowering verbosity

---

manticore/__main__.py
manticore/platforms/linux.py

As requested in Slack:
* a new parameter `--file` to add symbolic files
* a very simple symbolic seek implementation (current `seek` lacks a `whence` parameter and fails with TypeError)
Edit: changed `symfile` to `file` for consistent naming

Expose symbolic files to command line interface, implement whence for symbolic seek

---

manticore/manticore.py

Previously `manticore helloworld` would show a warning about using an unlocked shared context

Fix warning during regular analysis

---

manticore/core/smtlib/expression.py
manticore/core/state.py
tests/test_state.py

Adds parameters allowing the user to specify an ID for taint tracking to `state.new_symbolic_buffer` and `state.symbolicate_buffer`. Also adds a property to `smtlib.expression.ArrayProxy` that allows the taint of the proxied ArrayVariable to be returned.

Add Taint Parameters

---

manticore/core/state.py

As of right now, this functionality is broken (see: #378, #373), and should arguably be more platform-specific (not all platforms necessarily have files)

Remove `state.generate_inputs`

---

manticore/core/executor.py
manticore/core/state.py
manticore/manticore.py

This PR implements tracking of symbolic branches in each `State` (specifically `state.context['branches']`). It does this using a new event: `forking_state`. Similar to `will_fork_state`, `forking_state` fires when a state fork occurs, however it fires once for each individual state forked, being passed the specific value that has been concretized. `will_fork_state` fires once on a general state forking event, being passed the collection of all concretized values. This is unsuitable for tracking symbolic branches per state because the `State` the event handler has access to during `will_fork_state` is the parent state, and not a child state. For tracking symbolic branches, we want to only modify the specific child state.
Points of discussion and controversy:
I think this is general enough …

Implement symbolic branch tracking in core, add new fork event

---

manticore/core/executor.py
manticore/manticore.py

We used to ignore the message and always log "Testcase generated" even if there was a more specific logging message like "Program finished with exit status: 0"

Fix testcase generation output

---

docs/api.rst
manticore/core/executor.py
manticore/core/state.py
manticore/core/workspace.py
manticore/manticore.py
manticore/utils/event.py
tests/test_workspace.py

Proposed implementation related to #373 
Fixes #373 
This implements `state.generate_testcase(name, description)` which can be used by hooks to arbitrary generate testcases to the workspace.
discussion
- api name? `state.generate_testcase`, `state.generate_inputs`, `state.dump_inputs`, `state.get_inputs`, `concretize_inputs`

Implement state.generate_testcase

---

manticore/core/state.py
tests/test_state.py

Fixes #450 
Fixes the typo that caused the bug, and adds a unit test to check that `state.generate_testcase` publishes the proper event. It's not easy to write a unit test that actually checks that a testcase is generated due to how the State is coupled with the Executor for this functionality.

Fix state.generate_testcase

---

CHANGELOG.md
setup.py

Updates changelog, bumps version number.
Includes update to 0.1.2 since we forgot to mention that it added thumb mode.

Manticore 0.1.4

---

manticore/core/executor.py
manticore/manticore.py
tests/test_binaries.py

Fixes a minor logging verbosity regression (load state messages were being logged on verbosity=1) (see #431)
Also improve test to check for this.

Fix logger verbosity and test

---

README.md
setup.py

Updates setup.py to install z3 via pip, and removes docs references to installing z3 via apt.
Fixes #219

Use z3-solver package

---

manticore/__main__.py
manticore/manticore.py
manticore/platforms/linux.py

- Manticore ctor
- Manticore classmethods
- Controversial Manticore.verbosity() refactor as felipe's been suggesting: what do yall think? I added it because `m.verbosity = 2`, while a nice interface, doesn't let you control logging verbosity of what happens during Manticore ctor. and now, in Linux, the binary is loaded during the Manticore ctor (vs when you call m.run())

Refactor CLI, and Manticore high level interfaces

---

manticore/utils/log.py

Older code set a custom format string on the global log handler, and added a context filter to add the required field to each log record. This will fail if manticore is used as a library and a non-filtered logger is used. This localizes custom handler only to manticore loggers.
Fixes #544

Localize log formatting changes

---

manticore/core/cpu/abstractcpu.py

This change moves from inline function definitions out of the critical path of AbstractCpu's execute method.

Move inline function definitions out of the AbstractCPU's execute method

---

examples/evm/seth.py
manticore/core/executor.py
manticore/core/workspace.py
manticore/manticore.py
tests/test_manticore.py

This change fixes Issue #550, where the Manticore workspace dumps state onto the filesystem. The fix works by using the `workspace_url` knob in the `ManticoreEVM` constructor. 
Signed-off-by: Cole Lightfighter <cole@onicsla.bz>

[fix] Issue #550: generates extra workspace folder

---

manticore/platforms/linux.py

Fixes #537 
If a linux program opens `/dev/tty`, and Manticore tries to save state, it will crash when `.tell()` is attempted to be called on the `/dev/tty` file object. This pr changes the `File` functions for saving and setting state to detects when that happens and handle it.

linux: Improve error handling if special files (/dev) are opened

---

manticore/platforms/evm.py

Check global_storage includes an entry at address before trying to load storage.
This fixes the SLOAD memory issue from #543, but it leads to another deeper bug:
```
assert isinstance(value,(int,long)) or isinstance(value, BitVec) and value.size==256
```
It seems to occur when the error condition in SLOAD uses a short-circuit return, i.e. doesn't return a value.
If SLOAD returns a WORD-length null byte-string ("0x00" * 32), then a stack underflow occurs:
```
evm.execute()
File manticore/platforms/evm.py, line 830, in execute
arguments.append(self._pop())
File manticore/platforms/evm.py, line 792, in _pop
raise StackUnderflow()
manticore.platforms.evm.StackUnderflow
```
Should the error in SLOAD raise an exception instead of returning a null byte-string?

Fix SLOAD invalid memory access

---

manticore/core/executor.py
manticore/platforms/decree.py

For some reason, there are certain syscalls that never appear in the DECREE syscall trace. This commit added them.

Added missing syscalls in decree syscall trace

---

manticore/core/executor.py

This PR implements a optimization to forking. Fixes #526 
Currently, when manticore has a symbolic PC, or other Concretize exception, it uses the `fork` function to fork execution for each solution to the symbolic expr (depending on the policy). Forking is expensive and among other things, involved touching the workspace (disk). In the case when there is only 1 solution, a fork is not necessary, the current state should simply continue with the expression set to the single concrete solution.
Before the PR you might see logs like this:
```
2017-11-14 15:56:09,994: [107126] m.c.executor:INFO: Forking, about to store. (policy: ALL, values: 0x4009e3, 0x4009d3)
2017-11-14 15:56:10,072: [107126] m.c.executor:INFO: load state 2
2017-11-14 15:56:10,171: [107126] m.c.executor:INFO: Forking, about …
```

Optimize forking when only one solution exists

---

manticore/__main__.py
manticore/core/cpu/abstractcpu.py

Fixes #556 
Fixes #591 
**Summary:** Add a --version cli argument in main.py
**Fix:**
* A "version" argument is included in the argument handler in main.py
- Version hardcoded in the code which should be updated every release
- Outputs the version information and exits the program
- Performed test in the dev environment
**Further Discussion:**
* Methods to access version variable from setup.py without causing any malfunction

Fix for issue 556 and 591

---

manticore/core/cpu/abstractcpu.py
manticore/core/cpu/arm.py
manticore/platforms/linux.py

Fixes to the SUB, BLX, and MOV instruction implementations
Gettid syscall implementation

Fixes for issue 587

---

manticore/core/cpu/abstractcpu.py
manticore/platforms/linux.py

We currently log syscall invocation from each syscall individually. This PR fixes that and adds a helper to expand strings.
Fixes #440.

Centralize system call logging

---

manticore/core/workspace.py

Changed save_trace to do f.write('0x{:x}\n'.format(entry))

Add newlines in .trace file generation

---

manticore/__main__.py
manticore/platforms/platform.py

Added help=argparse.SUPPRESS to help arguements:
- assertions
- buffer
- context
- names
- offset
Removed --replay argument.
Fixes #617

Hide legacy cli flags from cli help

---

manticore/__main__.py
manticore/seth.py

Currently, when we terminate a state because there were not enough funds in the sender's balance for the transaction,  we keep that state alive, causing it to produce new states when another transaction is executed. This results in redundant states. We can safely terminate a 'not enough funds' state because it has no effect on blockchain state.

evm: Make 'not enough funds' states finalized states

---

manticore/core/plugin.py
manticore/platforms/evm.py
manticore/seth.py

- Fixes a bug in tuple size in sol compile helper
- generate .tx.# files for tx in each state
- save the compiled bytecode in workspace as a convenience, if solidity was compiled.

Implement initial evm workspace, fix small bugs

---

manticore/seth.py

Minor bug-fix to match changes to internal `ManticoreEVM._compile` with `ManticoreEVM.compile`.
@feliam's updates to `seth.py` appear to have fixed #524.

Fix compilation bug related to issue #524

---

manticore/seth.py

Fix the following bug:
`address` is used at line [seth.py#L1055](https://github.com/trailofbits/manticore/blob/591d7b81d56dae88c441975e955fece9f489ff58/manticore/seth.py#L1055), but is uninitialized if `metadata` is `None`

Seth: Fix uninitialized address in _generate_testcase_callback

---

manticore/__main__.py
manticore/seth.py

looks like this now.
should the code coverage/reverted/alive states be on different lines?
```
[I] mark ubuntu /m/h/c/m/e/evm (dev-evm-output) ❯ manticore demo.sol
2017-12-19 13:16:17,972: [90830] m.main:INFO: Beginning analysis
2017-12-19 13:16:18,047: [90830] m.seth:INFO: Starting symbolic transaction: 1
2017-12-19 13:16:18,386: [90830] m.seth:INFO: Generated testcase No. 0 - REVERT
2017-12-19 13:16:21,811: [90830] m.seth:INFO: Generated testcase No. 1 - REVERT
2017-12-19 13:16:25,695: [90830] m.seth:INFO: Generated testcase No. 2 - REVERT
2017-12-19 13:16:29,769: [90830] m.seth:INFO: Generated testcase No. 3 - REVERT
2017-12-19 13:16:33,518: [90830] m.seth:INFO: Finished symbolic transaction: 1 | Code Coverage: 54% | Reverted States: 4 | Alive States: 1
2017-12-19 13:16:33,519: [90830] …
```

Improve evm cli output

---

manticore/seth.py

- output exit status
- terminate throw states
looks like this now, note the "STOP" at the bottom, instead of "Still Running"
```
[I] mark ubuntu /m/h/c/m/e/evm (dev-alive-state-status) ❯ manticore two_tx_ovf.sol
2017-12-22 12:26:06,538: [83605] m.main:INFO: Beginning analysis
2017-12-22 12:26:06,622: [83605] m.seth:INFO: Starting symbolic transaction: 1
2017-12-22 12:26:06,958: [83605] m.seth:INFO: Generated testcase No. 0 - REVERT
2017-12-22 12:26:10,269: [83605] m.seth:INFO: Generated testcase No. 1 - REVERT
2017-12-22 12:26:13,939: [83605] m.seth:INFO: Generated testcase No. 2 - REVERT
2017-12-22 12:26:17,839: [83605] m.seth:INFO: Generated testcase No. 3 - REVERT
2017-12-22 12:26:21,489: [83605] m.seth:INFO: Finished symbolic transaction: 1 | Code Coverage: 54% | Terminated States: 4 …
```

output the actual exit status when finalizing evm states

---

manticore/platforms/evm.py
manticore/seth.py

Since this func was added, _generate_testcase_callback was overrided in ManticoreEVM totally bypassing this function, which is now unused.

Rm unused evm workspace function

---

manticore/__main__.py
manticore/ethereum.py

Currently, the manticore ethereum cli uses coverage based logic for determining when to stop running symbolic transactions. This can be somewhat faulty currently due to bugs in coverage computation. It can be useful to manually be able to control the number of symbolic tx, for example, to limit unnecessary state exploration.
This adds a `--txlimit` flag to the CLI, whose argument must be a positive integer.

Add --tx flag to control symbolic tx

---

manticore/ethereum.py
manticore/platforms/evm.py

Set Solitidty Metadata before EVMAccount constructor.
Make EVMAccount name solver lazy
This pull request fixes #674

Fix metadata setting race

---

manticore/__main__.py
manticore/ethereum.py

To test, use multi.sol:
```
contract C1 { }
contract C2 { }
```
and the manticore cli:
```
$ manticore multi.sol --contract C1
2018-01-15 09:08:23,503: [17455] m.main:INFO: Beginning analysis
2018-01-15 09:08:23,523: [17455] m.ethereum:INFO: Starting symbolic transaction: 1
2018-01-15 09:08:23,654: [17455] m.ethereum:INFO: Generated testcase No. 0 - REVERT
2018-01-15 09:08:24,945: [17455] m.ethereum:INFO: Generated testcase No. 1 - REVERT
2018-01-15 09:08:27,154: [17455] m.ethereum:INFO: Finished symbolic transaction: 1 | Code Coverage: 100% | Terminated States: 2 | Alive States: 0
2018-01-15 09:08:27,170: [17455] m.ethereum:INFO: Results in /home/gustavo/projects/DevContest/mcore_QWzfbr
$ manticore multi.sol --contract C2
2018-01-15 09:08:30,541: [17566] m.main:INFO: Beginning analysis …
```

Added support to analyze solidity source code with multiple contracts using the --contract command line option

---

manticore/platforms/linux.py

This PR updates the Linux loader to use the new `force` parameter for writing data to clear the BSS section, instead of setting/resetting memory permissions.

Use the 'force' flag for bss zeroing

---

manticore/core/executor.py
manticore/ethereum.py
manticore/platforms/evm.py
manticore/utils/event.py

Manticore considers whether a tx tries to transmit more value than the sender's balance. If there is not, we should terminate the state, which is currently not done. Because it is not done, we end up with incorrect transactions for the state.
Fixes #720
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/724)

Fix incorrect number of transaction in certain states

---

manticore/ethereum.py

evm state_id -1 refers to a state that is only in memory no need to delete a file
Fixes https://github.com/trailofbits/manticore/issues/737
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/738)

Fix finalize

---

manticore/core/cpu/x86.py

Hey,
This little change speeds up the execution of `manticore` on x86/x86-64 targets by around ~8% (a super clunky estimate, measured only on one simple example). 
This has been tested on a binary compiled as `gcc main.c` which source code looks like this:
```c
#include <stdio.h>
int main(int argc, char* argv[]) {
if (argc < 2) {
printf("Usage: %s <password>", argv[0]);
return -1;
}
if ((argv[1][0] == 'a') && (argv[1][1] == 'b') && (argv[1][2] == 'c')) {
puts("Good password!");
return 0;
}
puts("Bad password!");
return 1;
}
```
Then I have done the profiling as follows:
```
(angr) [dc@dc:aarch_playground]$ python -m cProfile -o profiler_out /home/dc/.virtualenvs/angr/bin/manticore ./a.out +++
2018-02-17 10:11:46,955: [13584] m.manticore:INFO: Loading program ./a.out
2018-02-17 …
```

Speedup x86 execution by caching AMD64RegFile.all_registers

---

manticore/core/executor.py
manticore/core/workspace.py
manticore/ethereum.py

#724 introduced a regression in handling of queue and states. It is caused by an incorrect assumption that Executor.put and Executor.enqueue are the same, I forgot to check that arguments both of those are supposed to take.
This quick fix reverts the breaking change, however it would be nice to refactor ManticoreEVM to not access `Executor._workspace`, which is a private member. Ideally `Executor` should offer external APIs for managing the state queue.
Fixes #735
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/741)

Fix evm state handling regression

---

manticore/platforms/evm.py
tests/test_eth.py

Previously, `did_evm_execute_instruction` and other events did not fire for SELFDESTRUCT, RETURN, REVERT, etc, because these instructions raise exceptions as part of their implementation. They do now, which means our traces will be more complete, and detectors will be able to watch for these instructions also.
Fixes #690
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/722)

Emit events for exception raising evm instructions

---

manticore/core/smtlib/constraints.py
manticore/core/smtlib/expression.py
manticore/core/smtlib/solver.py
manticore/core/smtlib/visitors.py
manticore/core/state.py
manticore/platforms/evm.py
manticore/platforms/linux.py
tests/test_smtlibv2.py

Expression expanded to handle arrays to arbitrary sized values (not just 8 bits)
Previously Array represented smtlib arrays from Bitvec(?) to Bitvec(8). 
With this patch you can now have Arrays of any to any bitsize.  (usable for EVM storage for example)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/732)

Array value configurable. 8,16,32..256 bits (not prefixed to 8)

---

examples/linux/Makefile

This is a trivial change to help build the "linux" example without having to modify the Makefile. It is necessary if the Python interpreter has a different name (or place) than simply `python`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/774)

Let the Python interpreter be specified externally

---

manticore/platforms/evm.py

Fix an invalid index access for raw transactions pending
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/786)

Fix out-of-bound index in EVMWorld._process_pending_transaction

---

manticore/manticore.py

Its just better to have a clear message intead of pure `AssertionError` with code:
```
mant(angr) [dc@dc:~]$ manticore asd
File "/home/dc/.virtualenvs/angr/bin/manticore", line 11, in <module>
load_entry_point('manticore', 'console_scripts', 'manticore')()
File "/home/dc/Projects/manticore/manticore/__main__.py", line 110, in main
m = Manticore(args.argv[0], argv=args.argv[1:], env=env, workspace_url=args.workspace,  policy=args.policy, disasm=args.disasm)
File "/home/dc/Projects/manticore/manticore/manticore.py", line 171, in __init__
assert os.path.isfile(path_or_state), "The file or state %s doesn't exist" % path_or_state
AssertionError: The file or state asd doesn't exist
```
---
This change is [<img src="https://reviewable.io/review_button.svg" …

Add assertion msg when target file is not present

---

manticore/ethereum.py

contract['bin'] contains the bytecode for Ethereum contract. Solidity returns an empty string if it encounters a function without code.
If the contract is 
```
contract C {
function f();
}
``` 
Solidity returns a '' in the contract['bin'] field. 
If the contract is 
```
contract C {
function f() {
}
}
``` 
Solidity returns bytecode in the contract['bin'] field.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/797)

Raises exception for contract with a function without code. Issue #789

---

manticore/platforms/evm.py
tests/binaries/780.sol
tests/test_binaries.py

Fixes #780 
Fixes #718
Off by one error in the code that checks if we are doing an out of bounds read. Previously, this code fell through to the `else` where it IndexErrored when it did a real out of bounds read on the underlying self.bytecode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/812)

Fix off by 1 error in codecopy

---

manticore/ethereum.py
manticore/manticore.py
tests/binaries/795.sol
tests/test_binaries.py
tests/test_eth.py

Fixes #795 
Fixes #802 
Rather than assertion error'ing out when there are no states, to run, simply return.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/815)

Graceful exit when no states to run

---

tests/binaries/799.sol
tests/binaries/807.sol
tests/test_binaries.py
tests/test_eth.py

Hi! I am new to the codebase, and this is my first PR.
My proposed change removes two tests that use inline contracts from `tests/test_eth.py`, and rolls them into the `test_eth_regressions()` method in `tests/test_binaries.py`.
I added a `contract` keyword argument to the `_simple_cli_run()` method, so that `.sol` files with multiple contracts can be run.
I believe this fixes [issue 809](https://github.com/trailofbits/manticore/issues/809). Please let me know if there is more to be done, or if my PR should be improved, for that issue to be satisfied.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/820)

port ethereum tests to individual files (issue #809)

---

manticore/__main__.py
manticore/ethereum.py

This addition will enable casual users to control how to test contracts using the manticore cli.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/819)

Added --txaccount parameter to control the caller of the symbolic exploration of smart contracts

---

manticore/ethereum.py
tests/test_eth.py

previously, we would report the 'visited.txt' which is the complete coverage that all states achieved, but it's often desirable to see what trace a particular state took. this implements some changes to the workspace files. we now emit a `.init.trace` and `.rt.trace` for the init and runtime traces for the state.
open to aesthetic suggestions for the divider. the '---' helps separate the individual traces of the various tranasactions within the file.
the colon delimiter was specifically chosen as it is ethersplay compatible https://github.com/trailofbits/ethersplay/blob/8c8934a03b4dc50ec6145573f7c35583d1213918/ethersplay/coverage.py#L17
this pr was expanded to also correct bugs in the trace recording (it was missing the last instruction of a trace (return/stop/revert)), and adds a test to …

evm: add per state trace file

---

tests/test_abi.py
tests/test_armv7_bitwise.py
tests/test_armv7rf.py
tests/test_driver.py
tests/test_eth.py

The `Armv7RF` class has 8 tests while only 7 were launched during test runs.
The problem was that we had two tests with the same name: `test_flag_wr`.
The first one can be found few lines above the second https://github.com/trailofbits/manticore/compare/master...disconnect3d:fix-duplicated-armv7-test-name?expand=1#diff-a4f83ac12d210376031ccbf8e84c0294R23
I have also refactored the file in 2nd commit (and removed unused imports).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/833)

Fix duplicated armv7 test name

---

manticore/core/smtlib/expression.py

This fixes one of the issues that is causing test_armv7cpu.py to fail when tested under python3.5
In python3 there are changes to how you are supposed to handle
overrides of __eq__, as it relates to __hash__
(http://python3porting.com/preparing.html?highlight=hash#implementing-hash)
In python2 we changed __eq__, but did nothing for __hash__, so __hash__
kept using the default one provided by object. In python3 it automatically
sets __hash__ to None, so we need to explicitly emulate this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/835)

Explicitly override __hash__ to use object.__hash__

---

manticore/core/smtlib/solver.py
manticore/utils/event.py

Py3 changes how subproc file objects are handled; by default they are byte (not str) oriented, and _are_ buffered (not unbuffered). This pr manually specifies that we want a line buffered, text stream to communicate with.
This makes test_armv7cpu.py pass all tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/836)

Open subproc in line buffered text mode

---

manticore/ethereum.py

If **asm_offset** is not present in the srcmap, a KeyError is raised. The KeyError is caught and an empty string is returned.
If **asm_offset** is present in the srcmap, the appropriate source code is written to summary as before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/839)

Added KeyError Exception for offsets not in srcmap. Issue #832

---

manticore/ethereum.py
tests/test_eth.py

Bug introduced in https://github.com/trailofbits/manticore/commit/0fc4bba9ad8ef61f9e1f23bc6d0a88b7a05aa385#diff-6cf4568b5e8712514d226faa04e417fbR450
- Move empty string up to the beginning of the if-else chain.
- Correct test for bool type case
Test `tests/test_eth.py:EthAbiTests.test_empty_types` added in https://github.com/trailofbits/manticore/commit/317d4277452e48ddb569eaddbf616fd41f99f4b9 and now passes.
fixes #869
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/872)

Fix Issue #869

---

manticore/ethereum.py
tests/test_eth.py

See http://solidity.readthedocs.io/en/v0.4.21/types.html#function-types
This is a special case of `bytes24`, 24 bytes are right zero padded in a 32 byte word.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/874)

Support ABI parsing of specs that use function types

---

manticore/platforms/linux.py

Manticore assumed that new calls to brk(2) were always increasing the
size of the data segment. This is not always true, since programs may
decide to reduce it as well.
Tested with a static Linux/i386 program on macOS/amd64.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/860)

Remove assertion on brk()

---

manticore/ethereum.py
tests/test_eth.py

Issue #705 reports that Manticore doesn’t support Solidity code with imports.
This is because Manticore currently only supports loading source code via strings.
This PR adds support for compiling code via a file handle, which then allows the Solidity compiler to resolve the imports.
---
This preserves the current behavior of using a string value as Solidity
source code, but now also supports instances of the `file` type, and
will use the `name` property of the file object to pass to the
subprocess invocation of solc.
This implementation also now ensures resource cleanup for the stdout and
stderr pipe handles.
---
fixes #705
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manti …

Support Solidity compilation of a file handle

---

manticore/ethereum.py

OSError thrown by subprocess.py is caught to alert the user that Solidity complier has not been installed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/877)

Added exception for Solidity compiler not installed. Fixes Issue #867

---

manticore/platforms/linux.py
tests/test_linux.py

Really this return EPERM (permission denied), which seems to be absolutely fine
since a non-privileged user is currently assumed. This is what would normally
be returned in this scenario.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/891)

Partially implement chroot(2)

---

manticore/platforms/linux.py

Really this return ENOSYS (not implemented), which allows sub-processes to
detect the condition and continue to run (or crash on their own if they did not
expect fork() to fail).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/892)

Partially implement fork(2)

---

manticore/ethereum.py
manticore/platforms/evm.py

Encountered the following trace:
```
…, in <module>
m.last_return()
File "…/manticore/ethereum.py", line 906, in last_return
return state.platform.last_return
AttributeError: 'EVMWorld' object has no attribute 'last_return'
```
It appears this bug was introduced in commit ed29a22f
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/886)

Typo in ManticoreEVM#last_return

---

examples/evm/minimal.py
manticore/ethereum.py

Refactor report generator to handle bytecode only contracts (no metadata) again. RFC/WIP
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/889)

Rollback to old mini assembler only example

---

manticore/platforms/linux.py
tests/test_abi.py
tests/test_armv7rf.py

The Linux platform initialization opens `stdin`, `stdout`, and `stderr` and ensures that they get assigned the correct fd values (0, 1, and 2). This is done inline inside an `assert`. If running with optimizations enabled (e.g. `PYTHONOPTIMIZE` is set), those fd's will not be opened and `__setstate__`/`__getstate__` will fail.
This makes sure we open them correctly regardless of optimization.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/894)

Fix Linux initialization

---

manticore/platforms/linux.py
tests/test_linux.py

Fixes #169
Is this exhaustive ?
Is `repr` ok for the reports ?
Do you need tests for this ?
Example 
`manticore -v --env "var1=value1" binary arg1 arg2`
Then
`cat mcore_FgaI4o/test_00000000.argv `gives`['arg1', 'arg2']`
`cat mcore_FgaI4o/test_00000000.env `gives`['lol=oui']`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/863)

Add dedicated files for ARGV/ENVP in report

---

manticore/__main__.py
manticore/platforms/linux.py

Use of environment variable MANTICORE_LD_PATH
instead of LD_LIBRARY_PATH which is protected on MacOS
Fixes #93
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/878)

Add LD_LIBRARY_PATH type feature

---

manticore/platforms/linux.py

Fixes #898 - Changed `interpreter_filename `to `interpreter_path_filename`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/899)

Fixed variable name typo. Issue #898.

---

README.md
setup.py

Re #881.
```
$ pip install ~/projects/manticore/
Processing /home/matiasb/projects/manticore
Collecting capstone>=3.0.5rc2 (from manticore==0.1.9)
Using cached https://files.pythonhosted.org/packages/fd/33/d1fc2d01b85572b88c9b4c359f36f88f8c32f2f0b9ffb2d21cd41bad2257/capstone-3.0.5rc2-py2-none-manylinux1_x86_64.whl
Collecting pyelftools (from manticore==0.1.9)
Collecting unicorn (from manticore==0.1.9)
Using cached https://files.pythonhosted.org/packages/7f/44/e6dd134bd7cc2dccc83e57ce435881b452a04ad5412836ba8a8e6db98dc0/unicorn-1.0.1-py2.py3-none-manylinux1_x86_64.whl
Collecting ply (from manticore==0.1.9)
Using cached https://files.pythonhosted.org/packages/a3/58/35da89ee790598a0700ea49b2a66594140f44dec458c07e8e3d4979137fc/ply-3.11-py2.py3-none-any.whl
Collecting pysha3 (from …
```

Install capstone from next branch, optional via pip --process-dependency-links.

---

scripts/travis_install.sh

The current test suite passes because at some point in the past the z3 solver was installed into the environment and the result was cached by travis. If, for whatever reason, travis fails to load the cache, tests fail since the current install scripts do not install z3.
This adds z3 to the installer to fix that issue. I would have added it to the actual dependencies of manticore itself, but since z3 is obtained via subprocess presumably we don't want to define a specific way that users have it installed and rather just want to document that it must be available on `PATH`.
Extracted from #905
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/906)

install z3-solver in our install script so it's available

---

manticore/__init__.py
manticore/__main__.py
manticore/binary/__init__.py
manticore/core/cpu/abstractcpu.py
manticore/core/cpu/x86.py
manticore/core/executor.py
manticore/core/parser/parser.py
manticore/core/plugin.py
manticore/core/smtlib/__init__.py
manticore/core/smtlib/constraints.py
manticore/core/smtlib/expression.py
manticore/core/smtlib/operators.py
manticore/core/smtlib/solver.py
manticore/core/smtlib/visitors.py
manticore/core/state.py
manticore/ethereum.py
manticore/manticore.py
manticore/platforms/decree.py
manticore/platforms/evm.py
manticore/platforms/linux.py
manticore/platforms/platform.py
manticore/utils/emulate.py
manticore/utils/helpers.py
manticore/utils/iterpickle.py
setup.py
tox.ini

This is the beginning of getting to a lint-clean codebase (As discussed here: https://github.com/trailofbits/manticore/pull/904#issuecomment-393189013). The flake8 configuration I used has been added to the `tox.ini`, but there are a few caveats:
* We're not clean even under this restricted set at the moment. Some of that is because we're not done, but some of it appears to be code that may not actually work right now and hasn't been caught since it isn't tested. We'll have to figure that out later.
* Many of the disabled checks should be re-enabled eventually, but we'll fix those in future PRs.
* No linting has been performed against the scripts or tests (for now).
So what was actually done in this PR?
* Several duplicate function/class definitions were removed.
* Imports in `__init__` …

Incremental Linting

---

manticore/binary/__init__.py
manticore/core/cpu/abstractcpu.py
manticore/core/parser/parser.py
manticore/core/smtlib/solver.py
manticore/platforms/decree.py
manticore/utils/iterpickle.py
scripts/benchmark.py
scripts/follow_trace.py
scripts/gdb.py
scripts/qemu.py
scripts/stats.py
scripts/verify.py
tests/auto/make_dump.py
tests/auto/make_evmtests.py
tests/auto/make_tests.py
tests/auto/trace.py
tests/test_armv7_bitwise.py
tests/test_cpu_manual.py
tests/test_eth.py
tests/test_linux.py

print statements, octal literals, and various small changes to support identical calling between py2 and py3. Plus a few missed exception syntax, etc. There will surely be more...
refs #904 
(This may not pass until it gets rebased against #907 but if it does then it's good to review/merge)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/908)

incremental py3: print statements, octals, and more

---

manticore/platforms/evm.py

Fixes issue #912. Recursive calls now work.
```from manticore.ethereum import ManticoreEVM
m = ManticoreEVM(workspace_url="bug")
m.verbosity(3)
owner_account = m.create_account(balance=1000)
c = '''
contract C1 { 
function f() returns (uint) {
return 1;
}
}
contract C2 { 
address c;
function C2(address x) {
c = x;
}
function f() returns (uint) {
return C1(c).f();
}
}
'''
c1 = m.solidity_create_contract(c, owner=owner_account, contract_name='C1')
c2 = m.solidity_create_contract(c, owner=owner_account, contract_name='C2', args=[c1.address])
c2.f();
c2.f();```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/917)

Fix pos CALL/DELEGATECALL/STATICCALL/CALLCODE

---

scripts/travis_install.sh
setup.py

#843 accidentally removed the z3-solver dependency from our setup.py. This PR adds it back, and removes the manual install line that was added.
https://github.com/trailofbits/manticore/pull/843/files#diff-2eeaed663bd0d25b7e608891384b7298R11
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/923)

Fix z3 install regression

---

manticore/ethereum.py

Use communicate() instead of `stdout.read` and `stderr.read`, as they can result in deadlocks. This can occur if manticore tries to compile a solidity contract that has enough errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/920)

Use p.communicate() to read stdout and stderr

---

manticore/platforms/linux.py
tests/test_linux.py

When manticore generates a testcase, it creates workspace files with concrete input, for example for stdin. It should do this for input coming from symbolic files, but it didn't used to -- this PR adds it.
Also corrects a bug where the `__getstate__/__setstate__` methods of SymbolicFile didn't call the parent methods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/928)

Generate symbolic file testcases

---

manticore/platforms/linux.py
tests/test_linux.py

#928 had a bug where files that were closed would not generate testcase content.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/929)

Make SymbolicFile testcase generation work for closed files

---

manticore/core/cpu/arm.py
tests/test_armv7cpu.py

Same as utxb but with halfword instead of byte
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/935)

Add UTXH to arm instructions

---

manticore/platforms/linux.py

Fixes #824 
Inode number from stat is either encoded on 32 or 64 bits
Since this is function `sys_fstat64`, I suggest that we use 64 bits.
Do you see any other way to get `sizeof(ino_t)` ?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/897)

Inode number is encoded with 64 bits

---

manticore/ethereum.py
tests/test_eth.py

This makes it possible for manticore to compile contracts that use build systems such as truffle to import external libraries such as openzeppelin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/945)

Allow users to specify path to solc and solc import remappings

---

manticore/ethereum.py

A quick fix of the regular expression on the function signature to allow numbers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/953)

Allow function identifiers on smart contract to have numbers on them

---

manticore/platforms/evm.py

The block hash calculation used to live within the implementation of the `BLOCKHASH` EVM opcode in the `EVM` class. This change moves that code to a new `block_hash` function in `EVMWorld` that can calculate arbitrary block hashes (not just limited to those mined within the past 256 blocks).
Fixes #957 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/958)

Moved block hash calculation to EVMWorld and genericized it

---

.travis.yml
scripts/travis_install.sh
scripts/travis_test.sh

This PR enables the reporting of test coverage of all the test jobs (`eth` and `tests`) to CodeClimate. This uses S3 to temporarily store results between jobs and later upload them to CC.
Fixes #1000
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1004)

Report test coverage to CodeClimate

---

.coveragerc
.travis.yml

This fix does two things:
1. Ignores non-manticore files from the coverage report to limit what can fail.
2. Changes how travis runs s3 sync on completion. (Fixes #1006)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1007)

Fix CC coverage

---

tests/test_linux.py

re #954 #955
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1022)

Add regression test for 954

---

manticore/core/smtlib/solver.py
tests/test_smtlibv2.py

Fixes #1021
This also should decrease how many times we invoke z3. (The instance used to query version should stick around)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1023)

Change how we query for version

---

.codeclimate.yml
manticore/core/cpu/abstractcpu.py
manticore/platforms/linux.py
tests/test_memory.py

- write/writev/read bugfixes
- add typing annotations
- resolves #1020 
- resolves #940
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1024)

fix sys_write logger output

---

tests/test_driver.py
tests/test_linux.py
tests/test_manticore.py
tests/test_models.py
tests/test_state.py
tests/test_unicorn.py
tests/test_workspace.py

Make test_manticore.py like test_binaries.py for path to binary to test
Otherwise, we get 
`Exception: tests/binaries/basic_linux_amd64 is not an existing regular file`
Related to #110
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1032)

Test manticore on MacOS

---

manticore/platforms/evm.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1039)

Fix mispelling in evm.py

---

CHANGELOG.md
manticore/__main__.py
setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1043)

Manticore 0.2.0

---

manticore/__main__.py
manticore/ethereum.py

The majority of the contracts we analyze everyday do not receive any ether (e.g. vanilla ERC20 ones). If Manticore tries to send ether to them, it will only generate useless test cases and slow down the analysis. That's why I believe it is useful to add an optional flag to avoid manticore to send ether when it is performing the symbolic execution of the transactions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1078)

Added --txnoether option to avoid sending ether to contracts

---

manticore/__main__.py
manticore/ethereum.py
tests/binaries/detectors/etherleak_true_neg.sol
tests/binaries/detectors/etherleak_true_neg1.sol
tests/binaries/detectors/etherleak_true_neg2.sol
tests/binaries/detectors/etherleak_true_neg3.sol
tests/binaries/detectors/etherleak_true_pos_argument.sol
tests/binaries/detectors/etherleak_true_pos_argument1.sol
tests/binaries/detectors/etherleak_true_pos_argument2.sol
tests/binaries/detectors/etherleak_true_pos_msgsender.sol
tests/binaries/detectors/etherleak_true_pos_msgsender1.sol
tests/binaries/detectors/selfdestruct_true_neg1.sol
tests/eth_detectors.py

this adds a detector ether leaks, and slightly refactors the detector tests
- make the LoopDepthLimiter plugin configurable (change the default to 5! the some for reason etherleak_pos_argument1.sol test needs 5, not 2 to work...)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1077)

eth: add ether leak detector

---

manticore/ethereum.py
tests/eth_general.py

This PR will make Manticore to print decoded arguments of the constructor and clearly show the result of its execution (RETURN or REVERT). For instance, using this contract:
```
contract C {
function C(uint x, uint y) {
require(x*y > 32);
require(x < 128);
}
function f() {}
}
```
you will get several test cases, for instance:
```
Transactions Nr. 0
Type: CREATE (0)
From: owner(0x5da83cffb5bab1cd888417a5ecefe37b9e250d67) 
To: contract0(0xca2410fda28718e5623a7a755531ae6dd30a28d2) 
Value: 0 
Gas used: 2300 
Data: b'608060405234801561001057600080fd5b506040516040806100f38339810180604052810190808051906020019092919080519060200190929190505050602081830211151561004e57600080fd5b60808210151561005d57600080fd5b505060868061006d6000396000f300608060405260043610603f576000357c01000000000000000000000000000000 …
```

Improved printing of constructor call with decoded constructor arguments and transaction result

---

manticore/__main__.py

Generating testcases for all discovered states can be extremely time consuming at the end of an analysis, and sometimes they are not even needed or desired. This adds a cli flag to suppress that part of manticore eth cli functionality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1083)

Add --no-testcases flag

---

examples/linux/Makefile

Ubuntu 18.04 doesn't alias python to python3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1122)

python3 update to linux example makefile

---

manticore/ethereum.py

Fixes the issue presented below:
```
➜ cat manticore_ex.py
from manticore.ethereum import ManticoreEVM, evm, Operators
m = ManticoreEVM()
source_code = '''
pragma solidity ^0.4.24;
contract Foo {
function foo() {}
}
'''
user_account = m.create_account(balance=1000, name='user_account')
contract_account = m.solidity_create_contract(source_code, owner=user_account, name='contract_account')
contract_account.foo(1)
print("[+] Now the symbolic values")
symbolic_data = m.make_symbolic_buffer(320)
symbolic_value = m.make_symbolic_value(name="VALUE")
symbolic_address = m.make_symbolic_value(name="ADDRESS")
symbolic_caller = m.make_symbolic_value(name="CALLER")
m.transaction(
caller=symbolic_caller,
address=symbolic_address,
data=symbolic_data,
value=symbolic_value
)
m.finalize()
print("[+] Look …
```

Fixes missing is_return_symbolic value

---

manticore/manticore.py

we used to get this line:
```
[I] vagrant ubuntu-bionic /v/manticore (dev-concrete-replay) ❯ manticore asd
File "/home/vagrant/.local/bin/manticore", line 11, in <module>
load_entry_point('manticore', 'console_scripts', 'manticore')()
File "/vagrant/manticore/manticore/__main__.py", line 207, in main
m = Manticore(args.argv[0], argv=args.argv[1:], env=env, entry_symbol=args.entrysymbol, workspace_url=args.workspace, policy=args.policy, concrete_start=args.data)
File "/vagrant/manticore/manticore/manticore.py", line 159, in __init__
raise Exception('{} is not an existing regular file'.format(path_or_state))
Exception: asd is not an existing regular file
Exception ignored in: <bound method Manticore.__del__ of <manticore.manticore.Manticore object at …
```

Fix err message if file doesn't exist

---

Dockerfile

An unfortunate interaction between the locale, python3, and unicode characters present in crackme.py led to an obtuse failure. Setting the locale to UTF-8 fixes it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1137)

fix building the examples in the docker container

---

manticore/utils/helpers.py

1. Does not check for `issymbolic `twice
2. Does not retrieve object taints when `int` was passed (and so is not tainted)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1133)

Simplify taint_with

---

manticore/core/executor.py
manticore/core/smtlib/solver.py
manticore/ethereum/__init__.py
manticore/exceptions.py
manticore/manticore.py
manticore/platforms/linux.py

this is partial, only the errors that were easy/straightforward.
i omitted evm and core/cpu because those seemed a little more involved, and also those might be subject to near term refactorings to try to reconcile evm and cpu (e.g. should an EVM actually be a CPU rather than its own class?)
todo:
- should it be named errors.py instead of exceptions.py
re #818

Global exceptions file

---

manticore/core/memory.py
tests/test_cpu_manual.py
tests/test_memory.py
tests/test_x86_pcmpxstrx.py

Previously pycharm would mark the `from abc` line as redundant.
but this is brittle because ABCMeta etc only happened to be imported
as a result of modules inside .smtlib importing ABCMeta. if we
followed pycharm's advice, and remove this abc import, and if solver.py
decided not to import ABCMeta anymore, this could would break.
so this makes it less brittle.

Explicit smtlib imports in memory

---

manticore/ethereum/__init__.py
manticore/platforms/evm.py
tests/eth_general.py

Fix sub issues 1 & 2 from here:  https://github.com/trailofbits/manticore/issues/1169
```
Missing analysis of valid JUMPDESTs. The EVM does not allow jumping into a data-section, for example into the 32 bytes following a PUSH32. So if the code is
PUSH01 5b
PUSH1 01
JUMP
Then it appears that manticore evm would jump into the 'artificial' jumpdest 5b at byte 1 and continue execution.
Missing JUMPDEST check. Apparently known already
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1172)

Fix Consensus-errors.1 & 2

---

manticore/core/state.py

```
Would it be possible to have, from a state, a function that solves a variable and concretizes it's solution in the state constraints ? 
It's a frequent mistake, from a user script level to have multiple symb variables, call `solve_one` on each variable, without concretizing the solution of each variable prior solving another one
Like if you have `a+b` and you look for overflow, the solver may tell you that a=1 and b=1 if you ask for the two solutions independently
```
This adds it to solve_one solve_buffer, which are the main APIs that make sense.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1182)

Add optional param to apply constraint to state

---

manticore/ethereum/__init__.py
manticore/ethereum/abi.py
manticore/ethereum/account.py

This adds a check and warning if a contract function is called with a number of arguments that does not match the signature.
The reason a warning is logged rather than an error thrown, is because passing an incorrect number of arguments to a contract invocation will result in an incorrect length tx data being used in the tx. If it's too short, the missing arguments will be implicitly zero (see yellow paper, oob reads in txdata are 0). If it's too long, the extra arguments won't be accessed by the contract. So imo neither case is technically "wrong".
Also refactors `EVMContract.__getattribute__` to be more readable using a namedtuple.
Fixes #1178
Running the script in the issue now produces
```
[I] (py3) vagrant ubuntu-bionic /v/m/1178 ❯ py x.py                         ❮ 10/08 05:39 …
```

Add check and warning for mismatched args

---

manticore/__main__.py
manticore/utils/log.py

This pull request implements #1158 .  A "--no-colors" command line flag was added to disable the insertion of ANSI color escape sequences, which are now outputted by default.  Currently, "DEBUG:", "WARNING:", "ERROR:", and "INFO:" should output in magenta, yellow, red, and blue, respectively, but these colors can be changed by editing the `coloring` dict object.
Since Manticore starts logging before command line options are parsed, there is a brief window during which ANSI color escape sequences might be outputted before the toggle to disable them takes effect.  In addition, if there are any starting points of Manticore's execution /other/ than `manticore/__main__.py`, then I may have failed to insert a check for the aforementioned command line toggle in those areas.
---
This change …

Colored Output

---

manticore/ethereum/abi.py

It used to falsely warn if there were 0 declared arguments, and 0 were given.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1191)

Fix logic in warning check

---

manticore/core/executor.py

**Fix for issue #1071**
**- Problem:**
* Global lock need to be held until the required variables are fetched
* Lock should be released while processing further
**- Fix:**
* Scope the lock loop only until the variables are set
**- Uncertain:**
* A similar scenario in `choice` function at Uncovered policy, should it be fixed as well?
* Do we have to explicitly unlock?
* Should there be any error handle for failures in lock loop?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1187)

Issue #1071  --> Global lock held for a long time

---

manticore/ethereum/__init__.py
tests/eth_general.py

This PR fixes issue #1196.
This PR also adds a test for the FilterFunctions fallback function hash matching to a new `EthPluginTests` class in `tests/eth_general.py`. Let me know if you the test to be moved elsewhere or done differently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1197)

Fix fallback function matching in ethereum.FilterFunctions

---

manticore/core/cpu/abstractcpu.py
manticore/core/cpu/x86.py

I hope that fixes #973 
It's been running for a while and I do not get the crash anymore (so the bug was probably in unicorn)
+ one commit to raise the verbosity of unimplemented instructions...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1120)

Implements some missing X86 XMM instructions

---

manticore/ethereum/__init__.py
manticore/ethereum/abi.py
manticore/ethereum/account.py
manticore/ethereum/solidity.py
manticore/utils/deprecated.py
tests/eth_benchmark.py
tests/eth_detectors.py
tests/eth_general.py

This draft PR is my proposed fix for issue #1210. It builds on PR #1211.
This PR currently
1. Rewrites `SolidityMetadata.__init__` to fix the handling of overloaded functions.
2. Separates the abi items for functions, events, constructor and fallback function into separate properties (though the event items are not yet publicly exposed).
3. Removes the `abi` property.
4. Removes the `add_function` method.
5. Adds a decorator for deprecating functions.
6. Deprecates the `functions` and `hashes` properties due to their problematic handling of the fallback function and adds `function_signatures` and `function_selectors` as replacements.
7. Deprecates the `get_hash` method, which seems redundant in its current form.
8. Adds static methods for constructing function and tuple type signatures …

Fix handling of overloaded functions and some other issues in SolidityMetadata

---

docs/syminput.rst
manticore/__init__.py
manticore/__main__.py
manticore/manticore.py

**Summary:** 
Fixes #170 --> add new cli argument for input_size and change function calls to include this argument
**Changes:**
* **Default value:** set default value for argument to 256 as hardcoded before
* **__main__.py:** add new argument for input_size 
* **make_linux, linux:** function call changes
**Clarification:**
* Default value for input_size to `256`? (as hardcoded before)
* Variable name set to `input_size`?
* The default value for argument is set at both argument `definition at arg parse` and `function definitions - make_linux, linux` which might be redundant? (make_linux call has a number of default arguments and linux function is a classmethod)?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Fixes issue #170: Cannot control input size from cli

---

.travis.yml
examples/evm/coverage.py
manticore/abitypes.py
manticore/binary/binary.py
manticore/core/smtlib/solver.py
manticore/manticore.py
manticore/platforms/decree.py
manticore/platforms/linux.py
scripts/gdb.py
tests/auto/make_evmtests.py
tests/eth_general.py
tests/test_binaries.py
tests/test_linux.py

This PR fixes all ResourceWarnings that are emitted in my Linux VM when I run the Manticore test suite like this: `PYTHONWARNINGS=error::ResourceWarning nosetests tests`
Fixes issue #1121 (opened by @yan)
This PR also fixes three invalid file open modes for binary files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1224)

Fix all ResourceWarnings triggered by the test suite

---

manticore/ethereum/abi.py

the problem: this should not warn!
```
In [16]: ABI.function_call('hi()')
2018-10-30 09:09:21,514: [8044] m.e.abi:WARNING: Number of provided arguments (0) does not match number of arguments in signature: hi()
Out[16]: b'\xa9\x9d\xca?'
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1227)

Fix warning logic

---

manticore/utils/mappings.py
tests/test_binaries.py

When mapping into memory uncommon ELF executables having their segments file
offsets not aligned on the system page size, the call to mmap_function() will
fail silently. It will actually return 0xffffffff, which isn't checked anywhere
and will only be detected when trying to read/write/free the memory area.
Because this ELF files triggering this issue are programmatically crafted from
binaries into a proprietary format, it won't be happening for all other
executables. But Manticore should support binaries as generic as possible.
This commit allows mapping into memory files having offsets not aligned on the
system page size by simply aligning the file offset when mmap'ing, and returning
a pointer shifted from the necessary correction. When munmap'ing the memory, the
address is aligned …

Allow file offsets not aligned on page size

---

manticore/utils/emulate.py
tests/test_unicorn.py

After the merge of the PR referenced at the end of this message into the master
branch of Unicorn in July 2016, the emulation mode is set according to the
least significant of bit of the program counter when it is updated.
When an instruction is not implemented at Manticore's level and emulation is
used, the PC value passed to the emu_start() function will trigger a switch of
the current mode, setting it back to ARM mode instead of Thumb mode. This commit
fixes this issue by ensuring that the least significant bit of the PC is set
when Thumb mode emulation is performed.
See https://github.com/unicorn-engine/unicorn/pull/592
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manti …

Fix emulation being performed in the wrong mode

---

manticore/ethereum/__init__.py
tests/binaries/imports_issue/main/main.sol
tests/binaries/imports_issue/utils/DirImported.sol
tests/binaries/imports_issue/utils/DirImported2.sol
tests/eth_detectors.py
tests/eth_general.py
tests/test_binaries.py

Having a `main.sol`:
```
pragma solidity ^0.4.25;
import '../utils/DirImported.sol';
import 'utils/DirImported2.sol';
contract C {}
```
and such directory structure:
```
$ tree
.
├── main
│   └── main.sol
└── utils
├── DirImported.sol
└── DirImported2.sol
2 directories, 3 files
```
and launching `manticore [options] main/main.sol` Manticore didn't respect current working directory and launched `solc [options] --allow-paths . main.sol` in `main` directory. As a result Manticore was failing due to `solc` being unable to import code from `utils` directory.
This PR fixes that issue and so Manticore will launch `solc [options] --allow-paths . main/main.sol` instead. A testcase has been added for that issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

Add support for cross directory imports

---

manticore/core/cpu/abstractcpu.py

This PR fixes the issue mentioned in https://github.com/trailofbits/manticore/issues/1236 by coercing the symbolic register value into a string prior to rendering it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1250)

Fixing "TypeError: unsupported format string"

---

manticore/core/cpu/arm.py
tests/test_armv7cpu.py

When two symbolic conditional instructions follow sequentially, the two paths of
the first instruction will be explored. But when the exploration reaches the
second instruction, because the at_symbolic_conditional flag has already been
set by the first one, only one of the two possible paths will be explored.
This commit fixes this issue by replacing the boolean flag by the address of the
instruction, which ensure the flag has been set for the current instruction.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1239)

Use the address of symbolic conditional instructions

---

manticore/core/cpu/arm.py
tests/test_armv7cpu.py

These 3 instructions can be used to load PC-relative addresses. The ADDW and
SUBW instructions can also be used with other source registers. When the PC
register is used as the source, the ARM documentation specifies that the offset
is added or subtracted from ALIGN(pc, 4).
See also the ARM Architecture Reference Manual Thumb-2 Supplement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1244)

Added ADR, ADDW and SUBW instructions semantics

---

manticore/core/cpu/arm.py
tests/test_armv7cpu.py

CBZ was not implemented while CBNZ was. As far as Manticore is concerned, CBZ is
the same as CBNZ, but with two possible destination addresses exchanged.
TBB and TBH instructions are often used for switches. According to the ARM
documentation, the base register contains the address of a table of
bytes/half-words, and the index register contains an index into this table. The
selected value is then shifted left by one and zero-extended to 32-bits before
being added to the current PC. If the PC register is used as the base, the table
is then located immediately after the instruction.
See also ARM Architecture Reference Manual Thumb-2 Supplement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Added CBZ, TBB and TBH instructions semantics

---

manticore/core/cpu/arm.py
tests/test_armv7cpu.py

STM and STMIB are already implemented. STMDA and STMDB simply call the helper
function _STM(). This function is modified to support decrementing the address.
See also ARM Architecture Reference Manual.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1245)

Added STMDA and STMDB instructions semantics

---

manticore/core/state.py
manticore/ethereum/__init__.py
manticore/utils/event.py

We previously did not copy the event system state such as
- `_signals`: the various event subscriptions
- `_forwards`: the various objects that events needed to be forwarded to
when a State object was copied.
This causes bugs like `State.generate_testcase` not working because the events are not forwarded to the `Executor` class.
This also adds a `forward_events_from` call in one place we forgot it.
This does a full copy of the `_signals` and `_forwards` so further mutation of the child state does not affect the parent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1215)

Copy event system state during state fork

---

manticore/ethereum/__init__.py

I ran into a situation where `source_file` was something like `../my/relative/path`, so the current code truncated the `working_dir`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1263)

Fix solidity relative path issue

---

manticore/core/state.py

```
2018-11-15 20:57:38,874: [15061] m.c.executor:ERROR: Exception: free variable 'e' referenced before assignment in enclosing scope
File "/home/vagrant/manticore/manticore/core/state.py", line 143, in execute
result = self._platform.execute()
File "/home/vagrant/manticore/manticore/platforms/linux.py", line 2230, in execute
self.current.execute()
File "/home/vagrant/manticore/manticore/core/cpu/abstractcpu.py", line 847, in execute
self.emulate(insn)
File "/home/vagrant/manticore/manticore/core/cpu/abstractcpu.py", line 875, in emulate
emu.emulate(insn)
File "/home/vagrant/manticore/manticore/utils/emulate.py", line 187, in emulate
"Concretizing for emulation")
manticore.core.memory.ConcretizeMemory: Concretizing for emulation
During handling of the …
```

Fix setstate reference before assignment

---

manticore/platforms/linux.py

Currently warns with an uninterpreted string instead of a useful error message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1281)

Add missing `f`-string

---

manticore/__main__.py

We inform about `combo1` when one passes a wrong `--txaccount` anyway, so we should also have it in `--help`:
```
$ manticore --txnocoverage --contract ModifierEntrancy --detect-reentrancy --txaccount asd ./test.sol
2018-12-10 02:43:11,831: [10019] m.main:INFO: Beginning analysis
2018-12-10 02:43:11,832: [10019] m.ethereum:INFO: Starting symbolic create contract
(...)
raise EthereumError('The account to perform the symbolic exploration of the contract should be "attacker", "owner" or "combo1"')
manticore.exceptions.EthereumError: The account to perform the symbolic exploration of the contract should be "attacker", "owner" or "combo1"
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Add combo1 to txaccount cli description

---

manticore/__main__.py
manticore/ethereum/cli.py
manticore/ethereum/manticore.py
tests/binaries/simple_int_overflow.sol
tests/eth_general.py

This PR implements a feature (enabled by default) to preconstrain the data of symbolic human transactions to avoid triggering uninteresting exceptions in the Solidity contract function dispatcher.
This PR fixes issue #731.
I've implemented the feature directly in `ManticoreEVM` and not e.g. as a plugin or in `EVMWorld` because there I also can constrain the transaction value depending on the function selector and thus avoid the 'not enough funds' fork in `EVMWorld._process_pending_transaction` for states that would lead to immediate REVERTs anyway. Doing it there also has the advantage that the constraint expression only is constructed a single time, not once for every running state.
With this PR applied, Manticore avoids all 6 states leading to REVERTs when it is run with the default …

Preconstrain the data of symbolic human transactions

---

manticore/core/manticore.py
manticore/ethereum/manticore.py
tests/test_binaries.py

For native binaries Manticore saves `command.sh` and `manticore.yml` in
a `_did_finish_run_callback`: https://github.com/trailofbits/manticore/blob/c29f7cf8672014cf02cfc1271ec1d0a3cb3983af/manticore/core/manticore.py#L524-L533
For ethereum smart contracts this callback is
called two times (not sure why), so we supress it instead: https://github.com/trailofbits/manticore/blob/c29f7cf8672014cf02cfc1271ec1d0a3cb3983af/manticore/ethereum/manticore.py#L1523-L1526
This PR moves this logic to a `ManticoreBase._save_run_data` method, so
it can be used in both native and ethereum Manticore engines.
As a result:
* native engine works as it worked
* ethereum engine will now save `command.sh` file
* ethereum engine will now print the elapsed time
Additionally, a bug with `command.sh` output has been …

Fix command.sh not saved in ethereum

---

manticore/ethereum/manticore.py
tests/eth_general.py

The `test_create_contract_two_instances` test was crashing before
this PR, due to calling `make_symbolic_buffer` twice with the same
buffer name (`'INITARGS'`) in `make_symbolic_arguments`.
Here's an example of such crash (from a bit different test code/when I
was developing it, but the idea/error is the same):
```
Error
File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
yield
File "/usr/lib/python3.6/unittest/case.py", line 605, in run
testMethod()
File "/home/dc/manticore_project/tests/eth_general.py", line 432, in test_create_two_instances_of_contract_no_args
contract2 = self.mevm.solidity_create_contract(source_code, owner=owner, args=None)
File "/home/dc/manticore_project/manticore/ethereum/manticore.py", line 587, in …
```

Fix multiple symbolic args solidity_create_contract

---

manticore/ethereum/cli.py
tests/test_binaries.py

```
root@52356aa06255:/# manticore test.sol
2018-12-12 13:53:58,615: [1496] m.c.manticore:INFO: Verbosity set to 1.
2018-12-12 13:53:58,798: [1496] m.main:INFO: Registered plugins/detectors: DetectInvalid, DetectExternalCallAndLeak, DetectEnvInstruction, DetectReentrancySimple, DetectUninitializedMemory, DetectDelegatecall, DetectUninitializedStorage, DetectReentrancyAdvanced, DetectUnusedRetVal, DetectSuicidal, DetectIntegerOverflow
2018-12-12 13:53:58,799: [1496] m.main:INFO: Beginning analysis
2018-12-12 13:53:58,800: [1496] m.e.manticore:INFO: Starting symbolic create contract
Mnemonic return
Mnemonic return hooman
2018-12-12 13:53:58,933: [1496] m.e.manticore:INFO: Starting symbolic transaction: 0
2018-12-12 13:53:59,072: [1496] m.e.manticore:INFO: 0 alive states, 2 terminated states …
```

Display registered eth detectors

---

manticore/core/executor.py
manticore/core/smtlib/constraints.py
manticore/core/smtlib/expression.py
manticore/core/smtlib/visitors.py
manticore/ethereum/abi.py
manticore/ethereum/account.py
manticore/ethereum/solidity.py
manticore/native/cpu/abstractcpu.py
manticore/native/cpu/cpufactory.py
manticore/native/cpu/disasm.py
manticore/native/cpu/register.py
manticore/platforms/decree.py
manticore/platforms/evm.py
manticore/platforms/linux.py
manticore/utils/emulate.py
manticore/utils/helpers.py
manticore/utils/nointerrupt.py
scripts/binaryninja/manticore_viz/__init__.py
tests/auto/make_tests.py
tests/mockmem.py
tests/test_abi.py
tests/test_cpu_automatic.py
tests/test_cpu_manual.py
tests/test_dyn.py
tests/test_linux.py
tests/test_slam_regre.py
tests/test_workspace.py
tests/test_x86.py
tests/test_x86_pcmpxstrx.py

There's no more old/new style classes in Py3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1307)

Remove Py3 redundant object inheritance

---

manticore/__main__.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1310)

__main__.py: fetch manticore version from installed module

---

manticore/ethereum/account.py
tests/eth_general.py

Proper fix for the (https://github.com/trailofbits/manticore/pull/1303) bug where we couldn't call a contract function that was prefixed with an underscore.
Before this PR we checked for attributes starting with an underscore in `__getattribute__`. If we found one - we used `object.__getattribute__(self, name)`.
This PR removes the check and uses `__getattr__` instead. This way, we don't have to handle the cases when we want to access `EVMContract` attributes as they just work as is.
Side note: https://stackoverflow.com/questions/3278077/difference-between-getattr-vs-getattribute
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1306)

Fix eth private func calls

---

manticore/native/cpu/arm.py

So accessing `operand.type` will now just return the value instead of building a mapping and getting a value for given key.
We will also fail fast if there will ever be an unrecognized type for a given operand.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1313)

Speed up ArmV7Operand.type assertions

---

manticore/utils/event.py
tests/test_events.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1314)

Refactor events and test_events

---

manticore/native/manticore.py
manticore/platforms/decree.py
tests/test_manticore.py

This PR adds symbol resolution through `core.Manticore.resolve()` for ELF binaries through DWARF debug information and symbol tables.
```
@m.hook(m.resolve('MyLib_function', line=4))
def hook(state):
m.terminate()
@m.hook(m.resolve('MyLib_otherfunc'))
def hook(state):
m.abort()
```
If the user does not supply a `line` argument, the first instance of the symbol will be resolved and its memory address will be hooked on.
I have yet to implement unit tests (if necessary), but this initial implementation seems to be working. Feedback for improvements and optimizations welcome!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1302)

Add symbol resolution feature for binary analysis

---

manticore/core/state.py
manticore/native/state.py
manticore/platforms/platform.py

The `StateBase` class had two properties that are only used in native engines: `cpu` and `mem`.
Those two used `self._platform.current` and that `current` is a property in linux and decree platforms that returns current process platfrom (?).
The PR also removes unused/redundant code in `StateBase`: `_init_context` and `record_branch` methods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1320)

Minor state/platform refactor

---

manticore/platforms/linux.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1319)

added warning and error to sys_arch_prctl

---

manticore/ethereum/detectors.py
manticore/ethereum/manticore.py
manticore/platforms/evm.py

This PR changes the `Transaction.is_human` method to a property and adds a docstring that explains what we understand as a "human transaction" along with an example.
The motivation for this change is that we had two places in the codebase where we used it **as if it would be a property while it wasn't**. This code is probably bugged - probably as I hadn't confirmed it with an example but certainly making `if tx.is_human:` would always be true:
https://github.com/trailofbits/manticore/blob/580b358678c471b252c381d1733b98a6a2ad9bde/manticore/ethereum/plugins.py#L51-L54
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1323)

Make is_human a property

---

manticore/platforms/evm.py

* Better debug strings (not enough gas reports the instruction and pc)
* Better comments
* Use f-string literal instead of `%` formatting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1329)

Minor evm refactor

---

manticore/__init__.py
manticore/__main__.py

We have this in setup.py python_requires but it doesn't work with old pip versions and we get reports that Manticore throws a SyntaxError (on a f-string literal :/).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1331)

Explicitly require Python>=3.6 when using CLI

---

manticore/ethereum/manticore.py

Changes default gas to 3000000 for `solidity_create_contract` and `create_contract`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1332)

Evm: change default gas to 3000000 when creating contract

---

manticore/core/smtlib/solver.py
manticore/ethereum/detectors.py

Gives love to the solver:
* reorganised imports (PyCharm auto optimize imports)
* compile regular expressions just once (!)
* refactored docstrings: fixed some parameter specifications, more type adnotations, use `"""` instead of `'''` (see https://www.python.org/dev/peps/pep-0257/)
* refactored the `_recv` method - moved its internal `readline` method to `__readline_and_count` method (so the `readline` method is not recreated each time we call `_recv`)
* refactored `_check()` method: it is now named `_is_sat()` and returns bool (or raises a `SolverUnknown` exception) instead of returning `'sat'` or `'unsat'` string
As a side effect of optimizing imports, detectors file imports have been fixed.
Note that some of the changes should speed up the solver a bit.
---
This change is [<img …

Refactor solver

---

manticore/ethereum/manticore.py

The method `last_return` is using a non-existing attribute `last_return_data`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1341)

Fix usage of non-existing attribute

---

manticore/core/executor.py

WIP
WIP
WIP
Add supporting methods
Move stuff to a plugin
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1357)

Dev state merging loadsave

---

manticore/platforms/linux.py

Per the [man page](http://man7.org/linux/man-pages/man2/lseek.2.html#RETURN_VALUE), `lseek` should return the offset location as measured in bytes from the beginning of the file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1355)

Make sys_lseek return offset location

---

manticore/__main__.py

The error message for first time users can be a bit confusing ("NameError: name 'native_main' is not defined"), if native deps isn't installed and the user is running the program against a binary file.
```
$ pip3 install manticore
[...]
$ manticore ./app
File "/home/user/.local/bin/manticore", line 11, in <module>
sys.exit(main())
File "/home/user/.local/lib/python3.6/site-packages/manticore/__main__.py", line 43, in main
native_main(args, logger)
NameError: name 'native_main' is not defined
```
After this patch, the code will instead return "ImportError: Missing some packages for native binary analysis. Please install them with pip install manticore[native]."
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

Ensure native deps (better error message)

---

manticore/ethereum/manticore.py
tests/ethereum/test_general.py

Fixes #1370
I assumed bytes to be the correct type since the evm implementation uses it. Also the code field is immutable so it seemed like a good fit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1371)

Fix ethereum Manticore API issue, where creating a new account with the code field failed

---

manticore/platforms/evm.py

For example, this provides a much more informative error about the lack of support for `STATICCALL` (see #1168).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1387)

More informative errors for unimplemented EVM features

---

manticore/platforms/evm.py

Failed internal transactions mistakenly used to pop 2 tx from the callstack and leave a STOP instead 
Fixes issue #1391
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1392)

Internal failed tx fix

---

manticore/ethereum/manticore.py

This allows solc-select (which runs in docker) to correctly access the relative path of a sol file.
I ran into an issue on Mac when using `solc-select` and running tests locally.
While this fix only makes _some_ tests cases pass, to get all `nosetests tests/ethereum` passing on Mac (and while using `solc-select`), crytic/solc-select/issues/8 needs to be resolved or taken into account.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1393)

Fix logic for solc relative path

---

README.md

This PR specifies shell examples in the README are bash. This PR does not introduce any new functionality outside of documentation enhancements
Signed-off-by: binaryflesh <logan.campos123@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1402)

Add bash syntax highlighting to shell examples in README

---

.travis.yml

An incorrect job count was making coverage uploading fail. We'll need to update this if we change the job count again in the future.
Going to merge this since it's a one-line change and it passes travis.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1409)

Fix Travis Coverage

---

manticore/native/cpu/x86.py

Found by profiling ais3_crackme from manticore-examples
Profiling result ie
`cat cprof.txt | awk '{print $2 $0}' | sort -n | tail`
gives
```
1.929   825101    1.929    0.000    4.210    0.000 helpers.py:13(issymbolic)
2.862      277    2.862    0.010    2.866    0.010 {method 'readline' of '_io.TextIOWrapper' objects}
3.491  1173293    3.491    0.000    3.742    0.000 x86.py:469(__contains__)
8.196   161737    8.196    0.000    8.196    0.000 {built-in method posix.read}
```
So x86.py:469(__contains__) is the second place where we spend the most time
The patch replaces the list by a set to get better performance for the `in` operation : O(1) instead of O(n)
Thanks to https://stackoverflow.com/questions/20234935/python-in-operator-speed/20234990#20234990
---
This change is [<img …

Performance optimization : use set instead of list

---

manticore/ethereum/manticore.py
tests/ethereum/test_general.py

When types consumed by a constructor are known this patch generates a reasonable set of arguments. Notably restricting the  size of dynamic arguments. 
Fix #1412
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1414)

Generates a more sensible symbolic default for constructor arguments

---

manticore/native/cpu/abstractcpu.py

Previously only supported ARM64 and x86. Now adds support for ARMv7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1429)

Add missing checks for ARM boundaries

---

manticore/native/cpu/aarch64.py
tests/native/test_aarch64cpu.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1433)

AArch64: fix ldrb size

---

examples/script/aarch64/hello42.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1439)

AArch64: do not use the 'procs' argument

---

Dockerfile
manticore/utils/emulate.py
manticore/utils/fallback_emulator.py
scripts/travis_install.sh
setup.py

This PR updates the Unicorn dependency.
Unfortunately, since Unicorn has not had an official release, I have pinned it to the latest commit in master at this time of PR. The method of pinning to the git commit is done in `setup.py`, but if there is a better way, I'm open to changing this. 
The git version pinning is only available in the latest `pip` versions, so I had to update Travis's pip version in the install script. Furthermore, in order to make `pip` use the git-pinned version, I had to add the `-I` option:
```
-I, --ignore-installed      Ignore the installed packages (reinstalling instead).
```
but it still seems to use the cache for already-existing dependencies that aren't updated remotely.
There is at least one issue when switching to the newest Unicorn, and that issue involves …

Unicorn dependency update

---

tests/native/test_unicorn_concrete.py

Rather than skipping this unit test, we should check that the set of known-matching registers still match in order to avoid any regressions.
Ideally, we should figure out why _all_ of the registers don't match, but it's yet unclear whether this is an actual issue, or if the final register differences are natural discrepancies that we can safely ignore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1437)

Hardcode expected matching concrete registers

---

manticore/native/cpu/x86.py
tests/native/test_cpu_manual.py

Adds support for `movhps`.
The implementation of `movhps` isidentical to `movhpd` since it moves two single-precision floats at the same time. As a result, we _could_ deduplicate the two into a single `movhp` or whatever method if desired.
Closes #1432.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1444)

x86: movhps support

---

manticore/__main__.py
manticore/native/cli.py
manticore/native/manticore.py

Refactored out the `coverage_file` param to get exclusively passed to the `Visited` plugin
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1442)

Relegate coverage file to plugin

---

scripts/travis_install.sh

It's --upgrade (or -U), not --update
I'm not sure why, but I guess Travis' build cache meant we didn't catch this ahead of time
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1445)

Fix invalid pip argument

---

examples/script/aarch64/basic.py
manticore/native/cli.py
manticore/native/manticore.py
scripts/sandshrew/sandshrew.py
tests/native/test_linux.py
tests/native/test_manticore.py

Modifies `native/Manticore` so that `m.init` hooks have the same API as they did before the executor refactor:
```
@m.init
def foo(state):
pass
```
as opposed to the current API of 
```
@m.init
def foo(m, ready_states):
for state in ready_states:
pass
```
Whereas the old `init` decorator simply subscribed the decorated function to `will_run`, this adds it to a set of init callbacks, and registers a separate `will_run` callback that loops over all decorated functions, then loops over all `ready_states`, and calls each callback with each state. This should be okay because `native/Manticore` should only ever have one starting state.
Note that this _doesn't_ change the API for the `will_run_callback`, which still takes `ready_states` as an argument. This is because the `m.init` function only …

Restore old init hook behavior

---

manticore/platforms/linux.py

More efficient to use deque for FIFO buffer of Socket data. O(1) for `popleft()` instead of O(n) for `insert(0, c)` https://docs.python.org/3/library/collections.html#collections.deque
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1453)

Use deque instead of list for FIFO queue in Linux Socket buffer

---

manticore/native/cpu/abstractcpu.py

If there is no check, an error will occur when trying to take `abs(arg)`.
Not sure if you want to do anything else with the symbolic argument or not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1452)

Fix check for symbolic syscall argument

---

setup.py

Our docs were partially broken because the lack of the native dependencies on RTD would result in import errors
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1457)

Install Native Dependencies when building on RTD

---

Dockerfile
scripts/travis_install.sh
setup.py

PyPi doesn't allow direct links to packages in the dependency specification, so we need to roll back #1440 and wait for Unicorn to push a new release in order to be able to deploy Manticore. See: https://github.com/pypa/pip/issues/5898
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1459)

Revert Unicorn Dependency Update

---

manticore/__init__.py
manticore/core/plugin.py
manticore/core/smtlib/__init__.py
manticore/core/smtlib/expression.py
manticore/core/smtlib/operators.py
manticore/core/smtlib/solver.py
manticore/core/state.py
manticore/ethereum/abi.py
manticore/ethereum/detectors.py
manticore/ethereum/manticore.py
manticore/native/cpu/abstractcpu.py
manticore/native/cpu/arm.py
manticore/native/cpu/x86.py
manticore/native/manticore.py
manticore/native/memory.py
manticore/native/models.py
manticore/platforms/decree.py
manticore/platforms/evm.py
manticore/platforms/linux.py
manticore/utils/emulate.py
manticore/utils/fallback_emulator.py
manticore/utils/helpers.py
tests/native/test_lazy_memory.py

Performance optimization avoiding runtime imports
Found by profiling ais3_crackme from manticore_examples with yappi (for multithreading profiling)
`issymbolic` was the leading function with 5.75 seconds in itself for about 2 minutes total execution
This change reduces it to 2.5 seconds
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1456)

Moving issymbolic to smtlib

---

.travis.yml
CONTRIBUTING.md
pyproject.toml

create a pyproject.toml so users don't have to worry about command line flags for black
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1466)

Enforce black formatting

---

manticore/core/workspace.py

Fixes https://github.com/trailofbits/manticore/issues/1479.
Simple check to ensure state's workspace URL does exist, and can still continue execution if it does not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1480)

Fix FileNotFoundError when loading existing state

---

manticore/core/manticore.py

I've spotted the typo while reading the docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1492)

Fix documentation typo in ManticoreBase

---

manticore/ethereum/manticore.py

Add a warning so people understand that we don't support solc 5+
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1488)

Add error for unsupported solc versions

---

examples/evm/complete.py
examples/evm/coverage.py
examples/evm/reentrancy_concrete.py
examples/evm/use_def.py

Update example syntax so they run under manticore 3.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1486)

Update evm examples

---

manticore/platforms/evm.py

Initial STATICCALL implementation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1494)

Patching STATICCALL

---

README.md
manticore/core/manticore.py

Adds deprecation warnings for the outdated API members as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1500)

Fix ReadMe Examples

---

README.md
manticore/ethereum/manticore.py
manticore/platforms/evm.py
scripts/travis_test.sh
tests/auto_generators/make_VMTests.py
tests/ethereum/EVM/test_EVMSHIFT.py

Closes #1166 
Adds instruction semantics and tests from [EIP-145](https://eips.ethereum.org/EIPS/eip-145).
Does not update for the Constantinople gas calculation semantics, or, for that matter, most of the other Constantinople changes. Further work will be handled in later PR's; the motivation behind this merge is to get the shift instructions into master sooner rather than later. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1498)

Add SHL/SHR/SAR

---

examples/linux/Makefile
examples/linux/crackme.py

I've found that the `crackme` example is compiled with optimizations which cut out certain branches and renders the description in `crackme.py` inaccurate. The result below is latest manticore from pip with gcc 8.3 (gcc version 8.3.0 (Ubuntu 8.3.0-6ubuntu1)) and `-Os` from the Makefile:
```
$ manticore crackme
2019-07-30 20:13:14,793: [10674] m.n.manticore:INFO: Loading program crackme
2019-07-30 20:13:15,393: [10702] m.n.c.x86:WARNING: CPUID with EAX=80000000 not implemented @ 402605
2019-07-30 20:13:21,917: [10674] m.c.manticore:INFO: Generated testcase No. 0 - test
2019-07-30 20:13:25,306: [10674] m.c.manticore:INFO: Generated testcase No. 1 - test
2019-07-30 20:13:28,907: [10674] m.c.manticore:INFO: Generated testcase No. 2 - test
2019-07-30 20:13:32,720: [10674] m.c.manticore:INFO: …
```

Update crackme example to match the description

---

manticore/core/smtlib/expression.py
manticore/core/smtlib/solver.py
manticore/core/state.py
manticore/core/worker.py
manticore/ethereum/__init__.py
manticore/ethereum/cli.py
manticore/ethereum/detectors.py
manticore/ethereum/manticore.py
manticore/platforms/evm.py
tests/ethereum/contracts/detectors/balance_not_ok.sol
tests/ethereum/contracts/detectors/balance_ok.sol
tests/ethereum/test_detectors.py
tests/ethereum/test_general.py

This taints the result of a BALANCE instruction and complaints if it is ever used in an EQ instruction.
Normally you can not trust the balance of an account as it can be incremented before the account is even created
The yellow paper first hints that the initial balance of an account is what is passed in the CREATE and then change its yellow mind over the formalization. So it seems developers tend to fall in this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1481)

Detecting the use of BALANCE in a strict comparison

---

manticore/native/cpu/x86.py

Python doesn't optimize those and repeats the same calculation 5 times. I've checked this on the following example:
```python
In [1]: def g(x):
...:     a = x // 2
...:     b = x // 2
...:     c = x // 2
...:     d = x // 2
...:     e = x // 2
...:
In [2]: import dis
In [3]: dis.dis(g)
2           0 LOAD_FAST                0 (x)
2 LOAD_CONST               1 (2)
4 BINARY_FLOOR_DIVIDE
6 STORE_FAST               1 (a)
3           8 LOAD_FAST                0 (x)
10 LOAD_CONST               1 (2)
12 BINARY_FLOOR_DIVIDE
14 STORE_FAST               2 (b)
4          16 LOAD_FAST                0 (x)
18 LOAD_CONST               1 (2)
20 BINARY_FLOOR_DIVIDE
22 STORE_FAST               3 (c)
5          24 LOAD_FAST                0 (x)
26 LOAD_CONST               1 (2)
28 BINARY_FLOOR_DIVIDE
30 …
```

Optimize repeated division in CMPXCHG8B

---

manticore/core/smtlib/operators.py
tests/other/test_smtlibv2.py

TLDR: `ORD(s)` should return something that has 8 bits instead of 7, which it incorrectly did for BitVecs with size>8.
Note that the `ORD` still does not support `BitVec`s with size<8, but I am not sure if we need that support for now. To be clear, such situation ends up as an assertion failure that is being done in `BitVecExtract`, so when assertions are gone (for optimized launches) we might want to extend `ORD` to support it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1512)

Fix operators.ORD for BitVecs of size > 8

---

manticore/core/smtlib/constraints.py
tests/other/test_smtlibv2.py

Previously the `new_bitvec` checked for `size == 1 or size % 8 == 0`.
This check allowed to create a bitvec with negative size, as in `cs.new_bitvec(-8)`.
It was also too constrained, as we might have cases where we want to constraint ourselves to e.g. 5 bits out of 8 bits of a byte). Sure, this can be done via setting a constrain over an 8-bit (1 Byte) bitvector, but it might be not the most efficient solution(?).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1511)

Fixes ConstraintSet.new_bitvec size check

---

manticore/native/memory.py
tests/native/test_memory.py

This is a better version of https://github.com/trailofbits/manticore/pull/1465.
This PR improves performance of `SMemory` concrete writes so we write concrete bytes in chunks instead of one by one.
Unlike #1465, this PR does not introduce `write1` which was a specialized `write` for single concrete bytes write.
I benchmarked master vs this PR vs #1465 via this code:
```python
import time
def test_write_concrete():
from manticore.core.smtlib import ConstraintSet
from manticore.native.memory import SMemory32
string = 'a' * 0x1000
mem = SMemory32(ConstraintSet())
buf = mem.mmap(None, 0x1000, "rw")
t1 = time.time()
for i in range(1000):
mem[buf:buf+0x1000] = string
t2 = time.time()
print(f"test_write_concrete: {t2-t1} seconds")
assert mem[buf:buf+0x1000] == [b'a'] * 0x1000 …
```

Improve performance of bulk read/writes to memory

---

examples/evm/mappingchallenge.py

https://github.com/trailofbits/manticore/blob/085c1d4d4558a8267a4873b6e157acc9ef361a6a/examples/evm/mappingchallenge.py#L67
The above line causes an assertion failure because the last argument should be an expression, not a string.  This pull request eliminates the last argument to that call, allowing it to default to `None`.

Fix assertion failure in mappingchallenge.py

---

manticore/utils/helpers.py

Note that these log messages are currently "invisible" as there is no
verbosity level that includes "manticore.util.helpers" in log.py.  These
log messages will be made visisble by a subsequent commit.

Add serialization/deserialization log messages.

---

manticore/utils/log.py

This commit does two things: (1) repair log "paths" that appear to be
non-existent/out-of-date, and (2) add the "manticore.utils.helper",
logging.INFO "path".
I added the new "helper" path to level 2, but I am open to changing
this.

Clean-up log

---

manticore/platforms/linux.py
tests/native/test_syscalls.py

This partial implementation does not handle src_addr and addrlen
arguments, which means this recvfrom acts like a recv syscall

Add partial implementation of recvfrom syscall

---

tests/native/test_memory.py

Adds test for memory max_exec_size

---

manticore/native/cpu/abstractcpu.py

Tested on example hxp2018_angrme
x86.py:696(read) drops from 900 000 calls to 500 000 calls
This results in a cumulative gain of about one second in abstractcpu.py:602(__getattr__)
For the last one, we must read again `self.PC` as `self._publish("will_execute_instruction", curpc, insn)` calls the hooks which may change the value of `self.PC`

perf: avoid multiple calls to read same self.PC

---

manticore/platforms/evm.py
tests/ethereum/test_regressions.py

Internal arithmetic must not be subject of 2^256 modulo.

ADDMOD and MULMOD fixes

---

manticore/ethereum/solidity.py

Fix srcmap parse when empty bytecode

---

manticore/binary/binary.py
manticore/platforms/linux.py

Keep track of open files and close them when done.

Fix ResourceWarning for open file stream leaks

---

manticore/core/smtlib/expression.py
manticore/core/smtlib/operators.py

fix #1463 
**Changes:**
* Adds `sdiv, rsdiv` methods
* Changes the calls to the respective functions
**Test:**
* Manual tested with corresponding logic_bomb
**Thoughts:**
* Reused similar implementation with respect to `srem, rsrem`
* There are a number of ways we could reuse already existing functions but reimplemented these functions to match existing flow.

fixes issue #1463 - adds signed division logic

---

manticore/platforms/linux.py

Limit the split to the first occurrence of an '=' character in cases
where the environment variable has value with equal signs

platform/linux: Fix env string parsing

---

manticore/core/smtlib/visitors.py
manticore/platforms/evm.py
tests/other/test_smtlibv2.py

This pull request simplifies `pc` using `simplify` in `visitor.py` whenever `pc` is set. This gives a significant speed-up whenever `DetectIntegerOverflow` is enabled. I think this is because that detector's use of taint cause `pc` to become symbolic, but in a way that can be simplified.
To demonstrate the speed-up, I performed the following experiment. I introduced `DetectIntegerOverflow` to eight examples in `examples/evm` and timed them using both the `master` and `simplify-pc` branches. I performed ten runs of each, interleaved to even out load spikes, and summed the timings of the corresponding runs. Results appear below.
To repeat my experiment, perform the following steps.
1. Drop the four scripts in [simplify-pc.zip](https://github.com/trailofbits/manticore/files/3581480/simplify-p …

Simplify the pc whenever it is set.

---

manticore/core/manticore.py
manticore/core/plugin.py
manticore/native/cpu/abstractcpu.py

Sometimes the "did_execute_instruction" failed to be fired after an int80 (native/x86)

Improvements in event publishing 

---

manticore/core/manticore.py
manticore/core/plugin.py
manticore/ethereum/cli.py
tests/native/test_manticore.py

Save profiling data into the workspace directory and not script directory.

Emit profiling.bin in workspace directory

---

manticore/core/smtlib/expression.py

Would like to give #1427 a try. This is my first shot at type hints in python.
**Changes**
* (Part 1) Removed `assert isinstances` for type checks with type hints in function arguments.
**Test**
* Manual test with `mypy`
**Thoughts**
* For positional arguments, we only need to match expected value for one such argument. [ Ref: https://github.com/python/typing/issues/270, https://github.com/python/mypy/issues/5876 ]. Currently, using `Any`, suggestions?
**References**
* https://www.python.org/dev/peps/pep-0484/
* https://docs.python.org/3/library/typing.html
* https://mypy.readthedocs.io/en/latest/cheat_sheet_py3.html
* https://www.pythonlikeyoumeanit.com/Module5_OddsAndEnds/Writing_Good_Code.html
* https://stackoverflow.com/questions/15853469/putting-current-class-as-return-type-annotation …

fix 1427 - limit sanity check in SMTlib

---

manticore/__main__.py
manticore/ethereum/cli.py
manticore/ethereum/manticore.py

It is common to only want to see the states alive when finalizing Manticore. This PR adds this feature at the cli and script level.
- Add `--only-alive-testscases` flag
- Add `only_alive_states` to `m.finliaze` (default False)

Add flag to only generate alive states when finalizing Manticore

---

manticore/core/manticore.py
manticore/core/smtlib/solver.py
manticore/ethereum/manticore.py
manticore/platforms/evm.py

This fixes some issues that would arise if you ran it under Python 3.8 (which no longer supports invalid escape chars in non-raw strings). For manticore to run cleanly under Python 3.8 we'll need to get https://github.com/ethereum/pyrlp to run a release as their last release has this same issue. They fixed it with https://github.com/ethereum/pyrlp/commit/bb898f8056da3973204c699621350bf9565e43df but haven't tagged a release since.

fix some deprecation warnings

---

setup.py

Moves `black` to the dev extra and makes `dataclasses` install only on Python < 3.7. This will make it so the `dataclasses` backport properly installs even when using a wheel.

reorg some deps a bit, usee env markers for dataclasses

---

.travis.yml
scripts/travis_install.sh
scripts/travis_test.sh
setup.py
tests/ethereum/test_sha3.py
tests/native/test_cpu_manual.py

This PR is meant to experiment with switching to pytest so that we can utilize it to refactor the tests after switching. The current set of changes:
* Removing `travis_wait` so we can see output during a test run. If there are tests that take >10 minutes this will cause a timeout and fail the job, which is likely why `travis_wait` was originally added, but if this is still an issue we can investigate other solutions that don't interfere with streaming stdout. **Update:** WASM tests cause timeouts. Added `travis-pls` to handle this while I investigate what's happening with those tests.
* Invoking `coverage run` with the `pytest` module and no checking of a `tee`'d log to determine whether to fail the job. I'm not entirely sure why that was there, but it shouldn't be required. If I'm wrong …

switch to pytest

---

.travis.yml

TLDR: This is not helpful when looking at `lint` build output:
```
$ black --check manticore/core/smtlib/solver.py
would reformat manticore/core/smtlib/solver.py
Oh no! 💥 💔 💥
1 file would be reformatted.
```
And this is more helpful:
```
$ black --diff --check manticore/core/smtlib/solver.py
--- manticore/core/smtlib/solver.py	2019-11-24 11:14:37.431508 +0000
+++ manticore/core/smtlib/solver.py	2019-11-24 12:09:00.461367 +0000
@@ -149,13 +149,11 @@
self._proc: Popen = None
parameters = "parallel.enable=true"
-        self._command = (
-            f"{consts.z3_bin} -t:{consts.timeout*1000} -memory:{consts.memory} -smt2 {parameters} -in"
-        )
+        self._command = f"{consts.z3_bin} -t:{consts.timeout*1000} -memory:{consts.memory} -smt2 {parameters} -in"
self._init = [
would …
```

Show black diff on travis builds

---

.travis.yml
scripts/travis_install.sh
scripts/travis_test.sh

This prevents us from seeing realtime output but in exchange I've made pytest fast-fail so jobs won't run past the first failing test. Not ideal but we'll keep improving

pytest-xdist prevents disturbing stdout, revert to travis_wait

---

.github/workflows/ci.yml
README.md
codecov.yml
examples/script/test_run_simple.c
scripts/travis_test.sh
setup.py
tests/native/test_aarch64cpu.py

This mostly just lifts and shifts us to GitHub Actions, but there are a few other changes:
* I made a physical file for the C binary that gets compiled for run_simple.py because EOF echoing requires hard tabs and that doesn't play nicely with yaml files.
* The tests will now run on a daily basis even if nothing is merged (this is useful to detect changes that result in failure on unpinned deps)
* We only run CI on master branch now, so if you want to see if your branch works (and you're not operating off a fork) you'll need to submit a PR. But really, just develop on a branch on your own fork 😊
* There is now a lint extra in setup.py
* Try out codecov forr coverage data. Code Climate's other features aren't particularly useful and it doesn't surface coverage data easily. Plus that s3 …

switch to github actions (take two)

---

manticore/utils/event.py
setup.py

Bumps the version number, enabling us to push a new PyPi build that will fix the installation issues on Python3.6. Since most of the changes since 0.3.2 have been to our CI, I'm going to forgo updating the changelog for now. Let's shoot for releasing 0.3.3 in the next couple of weeks and including Felipe's fakehash code.

Bump version to fix pip install on Python 3.6

---

manticore/native/manticore.py
tests/native/test_manticore.py

This makes it easier to direct Manticore at specified locations. We can
now add constraints that we want to be true before executing the next
instruction.
TODO:

Add option for hooking after instruction executes

---

manticore/platforms/evm.py
tests/ethereum/test_general.py

Currently, Manticore checks that the gas supplied is strictly greater than than the gas required by all operations.  This PR turns this "strictly greater than" check into a "greater than or equal to" check.

Fix gas check

---

.github/workflows/ci.yml

Remove the "all" option.  Make the error message a little more intuitive.

Simplify ci.yml

---

manticore/core/manticore.py
manticore/core/state.py
tests/native/test_resume.py
tests/wasm/test_state_saving.py

Adds a `SerializeState` exception that (ab)uses the concretization system to save a copy of the current state to the disk. Also adds a helper method to ManticoreBase that makes resuming execution from a saved state a bit cleaner. Overall, this should allow you to pause a concrete execution halfway through and then resume your analysis from there as many times as desired. 
Currently, this works for WASM and native. I haven't tried it with EVM. On WASM, the `run` method will happily start executing whatever's in the instruction queue without trying to invoke any functions. Likewise, the native `run` method starts executing wherever the PC is pointing - the call to `_start` actually takes place during the initial state creation.
This isn't a full-blown checkpoint system. From the tests, …

Streamline State Serialization Interface

---

manticore/core/smtlib/visitors.py

I've noticed that the `pwnable_collision` challenge in the manticore-examples repo is failing, as referenced in https://github.com/trailofbits/manticore-examples/issues/34
This PR is attempting to make minimal changes to the current code-base to try getting that test to pass.
* ~~`arithmetic_simplify` makes test_pwnable_collision in manticore-examples
repo hang. I'm not exactly sure what is happening, but there's probably
infinite recursion/walking/"simplification" happening somewhere. It still fails with this commented, but the next commit should make it work again...~~ ~~Looks like it was something to do with checking the wrong stuff for `visit_BitVecITE` in `arithmetic_simplify`~~ An inconsistency with using `expression.operands` and `*operands`?
* `visit` in `Visitor` and `_method` in …

Fix Regression(s)

---

manticore/core/smtlib/solver.py
tests/other/test_smtlibv2.py

Instead of trying all the values until the max/min is found this uses a binary search.
(Used only in the case the solver does not support the "optimize" command.)

Better iterative optimization for expressions

---

manticore/core/state.py
manticore/platforms/wasm.py
manticore/wasm/executor.py
manticore/wasm/manticore.py
manticore/wasm/structure.py
tests/wasm/generate_tests.sh
tests/wasm/test_callbacks.skip

Adds several helper methods to the WASM memory so as to conform to the standard laid out by native modules. Also lazily creates memory pages so that binaries can request large amounts of memory without Manticore needing to fill an appropriately large region with 0's.

Improve WASM Memory Ergonomics

---

manticore/utils/log.py
mypy.ini
tests/ethereum/test_detectors.py
tests/ethereum/test_sha3.py
tests/native/test_cpu_automatic.py
tests/native/test_cpu_manual.py
tests/native/test_memory.py
tests/native/test_state.py
tests/other/utils/test_config.py

Fixes #1608.
Additionally, this includes a few type annotations in a couple other places, which I added as I was looking there.

Use `mypy` to check the `tests` dir; fix some typing errors

---

.github/workflows/ci.yml
manticore/ethereum/cli.py
manticore/ethereum/plugins.py

This assumes nobody is using the result of REVERT and is not checking if the returned value is empty. Fixes https://github.com/trailofbits/manticore/issues/1593

Skip basic blocks that unavoidably end in REVERT.

---

.github/workflows/ci.yml

All of our pull request builds are failing right now due to (apparently) upstream changes to Truffle. Perhaps bumping the version number will be enough to fix them?

Attempt to fix Truffle tests

---

manticore/native/cpu/arm.py
tests/native/test_armv7cpu.py

Fixes #1621.
After cleaning some things up in the existing implementation, it became clearer how to make the decorator-based approach work, so I ended up going with that.
I added a bunch of additional unit tests as I did this work.

Add missing support for ARM modified immediate encodings

---

.github/workflows/ci.yml

This change merely passes an extra argument to `pytest` when it's invoked via GitHub Actions, so that the 100 slowest tests are reported.  This information is useful to identify possible places to tighten up the test suite.

CI: have pytest report 100 slowest tests

---

manticore/core/workspace.py
manticore/native/cpu/abstractcpu.py
manticore/native/manticore.py
manticore/native/models.py
manticore/platforms/evm.py
manticore/platforms/linux.py

It turns out that in smaller programs, like examples/linux/binaries/multiple-styles, something like 15-20% of total runtime is spent redundantly initializing the Z3 solver!

Swap remaining uses of `Z3Solver()` to use the singleton interface

---

manticore/platforms/linux.py

We support this syscall as a no-op, similar to the existing `sys_fadvise64` and `sys_madvise` syscalls.
With this addition, Manticore gets much much farther emulating some GNU Coreutils programs build for ARMv7 Thumb2.

Add support for `sys_arm_fadvise64_64`

---

.github/workflows/ci.yml
manticore/core/smtlib/solver.py
setup.py

Github actions is [currently failing](https://github.com/trailofbits/manticore/pull/1641/checks?check_run_id=564784041) to check out Manticore, possibly due to an outage.  Per slack, switching to checkoutV2 may fix it. 
Also updates Unicorn, black, and mypy to the latest versions.

Bump to CheckoutV2

---

lgtm.yml
manticore/core/plugin.py
manticore/core/smtlib/constraints.py
manticore/core/smtlib/solver.py
manticore/core/state.py
manticore/ethereum/abi.py
manticore/ethereum/manticore.py
manticore/native/cpu/aarch64.py
manticore/native/cpu/arm.py
manticore/native/memory.py
manticore/platforms/decree.py
manticore/platforms/linux.py
manticore/wasm/executor.py
manticore/wasm/structure.py
scripts/gdb.py
scripts/prof.py
tests/auto_generators/make_dump.py

Fixes the 10 errors displayed on [LGTM](https://lgtm.com/projects/g/trailofbits/manticore/alerts/?mode=list&severity=error&id=&tag=) right now. Also fixes several of the warnings, but not exhaustively.

Fix LGTM Errors

---

manticore/core/smtlib/constraints.py
manticore/core/smtlib/solver.py
manticore/core/workspace.py
manticore/native/cpu/abstractcpu.py
manticore/native/memory.py
manticore/platforms/linux.py
tests/ethereum/test_detectors.py
tests/native/test_linux.py

These added type hints get us three main benefits:
1. Static type checkers such as `mypy` can help identify inconsistencies in the code
2. Code understanding tools such as `jedi` (used in many editors for go-to-definition functionality) better understand the Manticore codebase
3. Humans may also have an easier time understanding Manticore APIs

Add type hints to several parts of Manticore

---

manticore/ethereum/manticore.py
manticore/platforms/evm.py
manticore/utils/helpers.py

Extract printable bytes from return data in the same way as it is
currently done for logs.

printable_bytes

---

manticore/native/cpu/abstractcpu.py
manticore/platforms/linux.py
manticore/platforms/linux_syscall_stubs.py
manticore/platforms/platform.py
mypy.ini
setup.py
tests/native/test_syscalls.py

Previously, using Typeguard with Manticore would break several emulated syscalls.  With this commit, it does not.
Some background information:
When a syscall is made from an emulated binary, Manticore uses the syscall number to look up the appropriate Python method that models that syscall, and then uses Python introspection to massage arguments to that syscall model function as deemed appropriate.
Previously, this mechanism used the deprecated `inspect.getfullargspec` to determine the number of arguments to the model function, and whether or not it takes varargs.
However, `inspect.getfullargspec` doesn't look through wrapper functions; it looks only at exactly the function object it is given. This is an issue, however, when trying to inspect _decorated_ functions. (The use of a decorator …

Rework syscall invocation for proper behavior under typeguard

---

.github/workflows/ci.yml
codecov.yml

This should prevent the red 'X' from appearing as soon as the first job finishes.

Make CodeCov wait for reports from all CI jobs

---

manticore/core/smtlib/constraints.py

There is a flaw in how __get_related works: when called on certain
unsatisfiable sets, it can return a satisfiable one. The flaw arises when:
* self consists of a single constraint C
* C is the value of the related_to parameter
* C contains no variables
* C is unsatisfiable
Since C contains no variables, it is not considered "related to" itself and is thrown out
by __get_related. Since C was the sole element of self, __get_related returns the empty
set. Thus, __get_related was called on an unsatisfiable set, {C}, but it returned a
satisfiable one, {}.

Disable core __get_related logic

---

manticore/ethereum/manticore.py
manticore/platforms/evm.py
manticore/utils/helpers.py
tests/ethereum/test_general.py

Some of these seem to have gotten passed over by our CI, which only checks files that have been modified by a given PR. Not sure how this happened, but `black` on my machine tries to reformat them every time I push code. Perhaps GH Actions will disagree?

Blacken a few more files

---

manticore/ethereum/manticore.py

Reverts one of the [changes](https://github.com/trailofbits/manticore/pull/1652/files#diff-e4836efb704ed46c30e5cfb02496a419R725) from #1652 to fix the sporadically-failing `test_integer_overflow_multitx_onefunc_feasible` test in `ethereum_bench`

Revert default gas limit

---

.github/workflows/ci.yml

This simply moves the ethereum truffle related smoke test to its own CI entity.

Move truffle to its own CI type

---

manticore/core/worker.py

Before this change:
```
m.c.worker:INFO: [0] Debug Concretize()
```
After this change:
```
m.c.worker:INFO: [0] Debug 'Concretize: Concretize PC (Policy: ALL)'
```

Improve concretize log messages

---

manticore/core/smtlib/solver.py

Option "tactic.solve_eqs.context_solve" was turned on by this commit in z3:
https://github.com/Z3Prover/z3/commit/3e53b6f2dbbd09380cd11706cabbc7e14b0cc6a2
Turning it off greatly improves Manticore's performance on [`test_integer_overflow_storageinvariant`](https://github.com/trailofbits/manticore/blob/96bfc80ea0545f67e9c335bb194f297051d51cdb/tests/ethereum_bench/test_consensys_benchmark.py#L106). Sample timings follow.
On commit [`96bfc80ea0545f67e9c335bb194f297051d51cdb`](https://github.com/trailofbits/manticore/commit/96bfc80ea0545f67e9c335bb194f297051d51cdb):
```
time pytest test_consensys_benchmark.py::EthBenchmark::test_integer_overflow_storageinvariant
...
real	11m45.771s
user	9m33.436s
sys	7m24.337s
```
After this change:
```
time pytest …
```

Disable "tactic.solve_eqs.context_solve"

---

docs/index.rst
docs/utilities.rst
manticore/utils/log.py

Setting `verbosity` on `ManticoreBase` appears deprecated, but the preferred method is not yet documented.

Add set_verbosity to the documentation

---

manticore/ethereum/manticore.py

The use of `self.world` in `solidity_create_contract` was causing a deprecation warning.  This PR fixes that.

Eliminate deprecation warning in solidity_create_contract.

---

manticore/ethereum/manticore.py

Manticore produces many log messages of the following form, and many of them are redundant:
```
m.e.manticore:INFO: Found a concrete globalsha3 ... -> ...
```
This PR makes it so that only one log message is generated for each new find.

Reduce concrete hash log messages

---

manticore/platforms/linux.py

Error message should now read:
manticore.platforms.linux.EnvironmentError: Trying to read from /proc/self/\<filename\>.
The /proc/self filesystem is largely unsupported.

Updated proc/self error message to show which proc/self filename is trying to be read

---

manticore/core/smtlib/constraints.py
manticore/core/smtlib/solver.py
manticore/ethereum/manticore.py
manticore/platforms/evm.py

Add __hash__ capabilities to ConstraintSet so we can use simple lru caching.
This improves commons case of re-doing the exact same query twice.
-baby steps towards query cache.

Add hashing to constraintSets

---

manticore/core/manticore.py
tests/other/test_locking.py

It looks like the `@sync` and `@contextmanager` decorators don't play nicely together. This PR is a check to see whether replacing the sync decorator with direct access to the lock breaks any tests.

Inline Sync Manager to Locked Context

---

.github/ISSUE_TEMPLATE/config.yml

Github automatically parses the issue templates and adds them to the config file, so they don't actually need to be included here.

Remove duplicated entries in issue config

---

.coveragerc
.github/workflows/ci.yml
codecov.yml
setup.cfg

Tells coverage.py to respect the top-level coveragerc file, and makes CodeCov tolerate a small drop in overall coverage percentage to account for nondeterministic gas tests.

Experimental coverage changes

---

manticore/core/smtlib/expression.py

This PR improves performance on serializing large ArrayStores. Pickling large ArrayStores would previously result in very deep recursion, which sometimes hit the python stack limit and caused a crash. Now, ArrayStores will iterate over their contents so that we instead pickle a flattened version.

Specialized iterative serialization for Array

---

README.md

Addresses #1771 (at least for the example in the readme). Increases the balance of the created account so the user has enough eth to send the contract creation transaction with the default transaction gas.
It's possible it would be more helpful to specify the gas for `solidity_create_contract` instead, but this keeps the example as simple as possible.

Update EVM usage example

---

README.md
docs/index.rst
docs/verifier.rst
manticore/ethereum/verifier.py

Readme updated to link to manticore-verifier documentation
Typos and output cleanups

Add doc, fix output bugs

---

manticore/ethereum/verifier.py
scripts/run_tests.sh
tests/ethereum/test_general.py

Switching from YAML to a script means that individual steps can fail, but the tests will still pass if the return value of the entire script is okay.

Capture return values in run.sh

---

manticore/core/manticore.py

Mprocessing uses a manager process to share data. It adds to much overhead in the common case.

Change the default to threading

---

manticore/core/smtlib/visitors.py

Remove thread unsafe global caching in expression simplifications.

Removing Thread unsafe global caching

---

manticore/core/smtlib/operators.py
manticore/core/smtlib/visitors.py

The EVM BYTE opcode with a symbolic offset argument needs the second handler or it asserts (first obviously on the offset == 0)
And I was seeing name collisions on the SMT vars, first I disabled threading to fix, but then added a lock around the unique variable.

Fix BitVec with symbolic offset and fix TranslatorSmtlib.unique thread safety

---

manticore/ethereum/manticore.py
manticore/ethereum/verifier.py
setup.py

- crytic-compile: use latest release
- manticore-verifier: enable crytic-compile cli flags
The crytic-compile version currently used by Manticore is out of date.
Additionally, `manticore-verifier` did not use the crytic-compile cli flags
To test this:
```
$ npx truffle unbox metacoin
```
Update `contracts/MetaCoin.sol` and add
```solidity
function crytic_test() public returns(bool){
return balances[msg.sender] > 1;
}
```
Then
```
$ manticore-verifier . --contract MetaCoin
$ rm truffle-config.js 
$ manticore-verifier . --contract MetaCoin --compile-force-framework Truffle --ignore-compile
```
The last command re-run Manticore, but fails without this PR

Improve crytic-compile support

---

manticore/platforms/linux.py

This partial implementation does not handle dest_addr and addrlen
arguments, which means this sendto acts like a regular send syscall

Add partial implementation of sendto syscall

---

manticore/platforms/evm.py
tests/ethereum/test_general.py

Addresses #1798 and adds some tests for selfdestruct gas costs.
The changes to `test_call_gas` make sure that it covers the account existence check.

Fix EVM account existence checks for selfdestruct and call

---

tests/ethereum/test_general.py

Fixes errors with `black` and the MacOS tests happening on `master`

Fix test regressions

---

manticore/wasm/structure.py

Change types.FunctionType=<class 'function'> to FunctionType

---

manticore/native/cpu/x86.py

`cpuid` with `EAX=80000000h` is meant to return the highest "extended function" ID back via `EAX`.
Both Intel's and AMD's docs are a little oblique when it comes to what exactly an "extended function" ID *is*, but it *seems* to just be another `EAX` value (i.e., `CPUID` "leaf") with the high bit (i.e. `EAX=8xxxxxxxh`) set.
Longer term, we should probably support some of these higher extended functions/leaves. In particular, it looks like recent versions of the Linux VDSO check for `CPUID EAX=80000001h` and then check if `EDX.RDTSCP[bit 27]` is high in order to use `rdtscp` (in lieu of `rdtsc` + a serializing hack?).

native/cpu/x86: Add support for CPUID EAX=80000000h

---

manticore/platforms/evm.py

As I understand it, this is necessary to get the [building secure contracts](https://github.com/crytic/building-secure-contracts) repo passing by default. It's also a frequent first step for real-world EVM analysis, so perhaps it will save some time.
The tests are performing suspiciously well locally. I would have expected some changes to be required. Let's see how GH Actions handles them.

Ignore Gas Calculations by Default

---

README.md
manticore/core/smtlib/solver.py

Try yices, if not present use z3

Detect default solver

---

manticore/core/smtlib/solver.py

```
$yices-smt2 --help
--timeout=<timeout>       Set a timeout in seconds (default = no timeout)
-t <timeout>
```

Fix yices timeout argument

---

examples/evm/minimal.py
manticore/ethereum/manticore.py
manticore/platforms/evm.py

```
owner_balance_symbolic = m.make_symbolic_value()
owner_account = m.create_account(balance = owner_balance_symbolic, name="owner_account", address = tx['from'])
```
generates the following error:
owner_account = m.create_account(balance = owner_balance_symbolic, name="owner_account", address = tx['from'])
File ".../.local/lib/python3.8/site-packages/manticore/ethereum/manticore.py", line 796, in create_account
raise EthereumError("Balance invalid type")
manticore.exceptions.EthereumError: Balance invalid type

Attempt to allow symbolic balances from the start

---

manticore/platforms/evm.py

There is a small typo in manticore/platforms/evm.py.
Should read `straight` rather than `straigth`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, straigth -> straight

---

.github/workflows/osx.yml
tests/other/test_tui_api.py

Prefer `solc-select` over `brew` for installing Solidity 0.4.x, as the latter doesn't seem to work on MacOS.

Attempt to Fix solc Installation

---

manticore/utils/config.py
manticore/wasm/cli.py
tests/other/utils/test_config.py
tests/wasm/test_examples.py

Extracted from #2394 
The `config` system is a little brittle when Manticore tries to import all platform modules since we set the config options upon import and declaring the same config option in two different platforms will cause issues.
This is a bit of a band-aid over the real problem, which might look something like moving shared `config` options to a separate file that each platform can import.
Looks to be some related refactoring work here https://github.com/trailofbits/manticore/pull/1636

Allow double-adding exact same config option

---

manticore/core/smtlib/constraints.py
manticore/core/smtlib/expression.py
manticore/core/smtlib/operators.py
manticore/core/smtlib/visitors.py
manticore/core/state.py
manticore/ethereum/abi.py
manticore/ethereum/manticore.py
manticore/native/cpu/x86.py
manticore/native/memory.py
manticore/platforms/evm.py
tests/ethereum/test_general.py
tests/native/test_cpu_manual.py
tests/native/test_driver.py
tests/native/test_register.py
tests/native/test_state.py
tests/other/test_smtlibv2.py

More minimal PR after breaking it out of #1729
This will help with multiple inheritance in a future commit. Also a better way to enforce correct initialization of the objects.
Follow-up to `slotted` branch/PR #2394

Expression use keyword-only arguments for init

---

.github/workflows/ci.yml
manticore/utils/install_helper.py

A very small change in an error message to use `pip3` instead of `pip`.

Update CI and suggest to use pip3 instead of pip

---

manticore/native/memory.py

The Memory class had a global solver hard-coded that resulted in z3 (or the solver the user has installed) always used when a native binary was executed. This PR should fix that.

Removed use of global solver from Memory

---

manticore/ethereum/manticore.py
tests/ethereum/test_general.py

This small PR can save a few calls to the SMT solver avoiding getting the EVM events by default. Fixes #2416

Disabled EVM events in testcases by default

---

manticore/core/manticore.py
manticore/core/smtlib/solver.py
manticore/ethereum/manticore.py
manticore/native/manticore.py
manticore/wasm/manticore.py

This small PR includes a global dictionary that keeps tracks of when each solver is used succefully, timeouts or returns unknown. At the end, the result will be saved in a plain text file called `global.solver_stats`. If the solver returned either timeout or unknown, the user will be warned about it.

Basic solver stats

---

examples/script/symbolic_file.py
manticore/platforms/linux.py
scripts/run_tests.sh
tests/native/test_integration_native.py
tests/native/test_linux.py

Addresses https://github.com/trailofbits/manticore/discussions/2453

Fix incorrect comparison for symbolic file wildcards

---

manticore/__main__.py
manticore/ethereum/cli.py
manticore/ethereum/verifier.py
scripts/run_tests.sh
tests/ethereum/test_regressions.py

Replaces the `quick_mode` flag with `thorough_mode` and inverts the logic so that the `quick_mode` configuration changes are now enabled by default. Closes #2424.

Replace Quick mode with Thorough mode

---

manticore/ethereum/manticore.py

This small change will hardcode the owner and attacker accounts in `multi_tx_analysis` to make results easier to read and it will force smt constraints to be the same at every run.

Use fixed owner and attacker accounts in multi_tx_analysis

---

scripts/run_tests.sh

This pinned version should be reverted when https://github.com/crytic/crytic-compile/issues/199 is fixed.

Install pinned version of truffle to fix CI

---

manticore/core/plugin.py
manticore/native/state.py

Start tracking `_last_pc` inside StateDescriptors. This is helpful for figuring out which instruction causes a state to fork.

Track last_pc in StateDescriptors

---

manticore/platforms/linux.py

The `interpreter_filename` variable extracted from ELF binaries can contain trailing null bytes. Those null bytes should be removed.

Fix loading custom interpreters for ELF binaries

---

.github/workflows/ci.yml
.github/workflows/osx.yml
.github/workflows/release.yml
README.md
examples/script/concolic.py
manticore/__init__.py
mypy.ini
setup.py

~Three days ago, the symbolic WASM tests started failing on `master`. There were no changes to manticore in between the failing tests and the passing ones. Presumably some kind of upstream update caused the failures, but Yices, Z3, and CVC don't seem to have published any releases that day. Interestingly, the failure always occurs in the `fib_L271`, which is a stress-test designed to test WASM functions with very high call depth. It also seems to take the form of SMTLib errors we've seen before, where an invalid SMT2 string is rendered into text and sent to the solver. For example, in today's failure, the exception is: `2021-07-23 12:12:49,417: [7396] m.c.worker:ERROR: Exception in state 0: SolverException('Error in smtlib: (error "at line 782, column 29: undefined identifier: BitV")',)`. …

Switch to Python 3.7

---

manticore/core/plugin.py

Track the parent of each state in StateDescriptors. This is helpful when generating a provenance tree for a given state.

Track parent in StateDescriptors

---

manticore/platforms/linux.py

By prioritizing `LD_LIBRARY_PATH`, it enables the ability to run binaries with custom loaders without any patching. This is useful when trying to run a dynamically linked binary with a specific version of libc which differs from the system default.

Prioritize LD_LIBRARY_PATH over system default path

---

Dockerfile

Manticore now requires Python 3.7

Fix Docker with updated Python

---

manticore/core/worker.py

This is useful for having more strict runs of Manticore where we want to know about any unrecoverable errors encountered during state exploration.

Option to kill Manticore if any state fails on unrecoverable error

---

manticore/core/manticore.py
manticore/core/state.py

This was added a while ago when loading states from their serialized
form in https://github.com/trailofbits/manticore/pull/1609 and this PR
makes this feature a bit more robust.

Add manticore reference property to States

---

manticore/native/cpu/abstractcpu.py
manticore/native/cpu/disasm.py

Helpful for knowing the exact last executed instruction address.

Add last_executed_pc property to abstract CPU

---

scripts/run_tests.sh
setup.py

This PR allows us to support Truffle version 5.3.14, which is now supported by the [latest release of crytic-compile](https://github.com/crytic/crytic-compile/releases/tag/0.2.1)

Unpin Truffle Version, Use Latest crytic-compile

---

manticore/native/cpu/aarch64.py

I am working on [new `mypy` feature](https://github.com/python/mypy/pull/11206) and it identified a problem with your `namedtuple` definitions.
https://github.com/python/mypy/pull/11206#issuecomment-962573633
By standard first string arg should match variable name.
Refs https://github.com/python/mypy/pull/11206

Improves `namedtuple` definition

---

manticore/platforms/linux.py

Some small improvements to the `Linux` platform: 
* Distinguish interpreter and program base addresses
* Serialise base addresses in `__setstate__` and `__getstate__`

Fix handling of the program base address in Linux

---

manticore/core/smtlib/expression.py
manticore/core/smtlib/visitors.py
tests/other/test_smtlibv2.py

This PR adds the following simplifications for expressions: 
`A-A ==> 0`
`A-0 ==> A`

Add SMT simplifications for bitvec subtraction

---

manticore/native/cpu/x86.py

While working on https://github.com/python/mypy/pull/11206 I found that `Regspec` definition is not ideal.
It is recommended to use the same string name, as variable name. 
For example, it affects how `pickle` works.
Related https://github.com/trailofbits/manticore/pull/2501
Related https://github.com/trailofbits/manticore/commit/6e036f3034b76bbecf36b5469e49294e038ff705

Improves namedtuple definition

---

manticore/core/manticore.py
manticore/core/state.py
manticore/core/worker.py

Add a new fork policy called "EXPLICIT" that allows to specify arbitrary concrete values for the expression on whom we are forking.

Add EXPLICIT fork policy

---

manticore/core/smtlib/visitors.py
tests/other/test_smtlibv2.py

This PR fixes an SMT simplification pattern for `BitVecExtract` on constants. 
The current implementation was ignoring the most significant bit of the extracted value.

Fix `BitVecExtract` simplification for constant folding

---

manticore/utils/fallback_emulator.py

As described in https://github.com/trailofbits/manticore/issues/2528, we need to exclude some FPU registers from the unicorn <-> manticore context switch when using the emulator, because those registers aren't supported in unicorn yet.
It turns out that the FPU registers also need to be ignored in the fallback emulator (different than the regular emulator), which is what this PR does.

Ignore missing unicorn registers in the fallback emulator

---

manticore/native/cpu/x86.py

Currently the `ENDBR64` instruction is implemented but `ENDBR32` isn't so there will be issues running 32-bit native x86 binaries with manticore. This should implement that `ENDBR32`.

Add ENDBR32 instruction

---

manticore/native/cpu/x86.py

Seeing as they're fancy NOP's, I don't think there's any reason not to merge them into `master`, and thus avoid aggressively concretizing the state in order to emulate them under Unicorn.
Thanks for the implementation, @lordidiot

Split off ENDBR32/64 from CHESS branch

---

manticore/core/manticore.py
tests/ethereum/test_general.py
tests/native/test_models.py
tests/other/test_fork.py

This PR improves the forking process when there is only one possible solution for the symbolic expression upon which we fork. In that case, we re-use the same `State`  instead of copying the entire state to create a new one.
I don't think that Manticore has many tests for forks except this one: https://github.com/trailofbits/manticore/blob/93211002a9cea6074790c0de974fb9e603881577/tests/native/test_models.py#L227-L263 
I did test this PR in CHESS, but we should add a Manticore testcase for forking on  a single solution since it hits a rarer and slightly different code path than regular forking.

Optimise forking when there is only 1 solution

---

manticore/native/manticore.py

noticed on the sphinx-generated docs that `entry_symbol` had no type specified and passing a string to `envp` didn't work, turns out there's a typo

fix typo in Manticore.linux constructor docstring

---

manticore/utils/log.py

Currently a test in `test_tui_api.py` is failing and the TUI itself doesn't send logs over as a protobuf message because the LogCaptureWorker's `log_callback` isn't being registered correctly. This PR fixes that!

Fix bug in register_log_callback

---

manticore/platforms/linux.py

Two changes in this PR
- Currently `sys_newstat`'s implementation is based on `sys_stat64`
- This is inaccurate because `sys_stat64` is expected to return a `struct stat64` back to userland [ref1](https://elixir.bootlin.com/linux/v5.17.5/source/fs/stat.c#L521) [ref2](https://elixir.bootlin.com/linux/v5.17.5/source/arch/x86/include/uapi/asm/stat.h#L42)
- Instead, `sys_newstat` is supposed to return a `struct stat` [ref1](https://elixir.bootlin.com/linux/v5.17.5/source/fs/stat.c#L380) [ref2](https://elixir.bootlin.com/linux/v5.17.5/source/arch/x86/include/uapi/asm/stat.h#L83)
- This causes issues because the two structs have different definitions, and in practice causes errors in the loader. For example "LD_LIBRARY_PATH" environment variable does not work. I suspect …

Fix newstat and newfstat syscalls

---

manticore/native/cpu/x86.py
tests/native/test_x86.py

Adds support for `psubq` x86 instruction. Implementation very similar to `psubb`.

Add `psubq` instruction (x86)

---

examples/README.md

`python3` will give `ModuleNotFoundError: No module named 'manticore'` error.

Use python3.7 instead of python3

---

setup.py

Allow any newer release than 0.2.2

Loosen crytic-compile version restrictions

---

setup.py

Only use a lower bound (not sure if the lower bound actually means
anything with regards to what Manticore _requires_, but better keep it
around just in case)

Loosen test dependency version constraints

---

manticore/core/smtlib/visitors.py
tests/other/test_smtlibv2.py

This PR adds the following simplification patterns on constraints that we often encounter within `MATE`:
```
!(a||b) -> !a && !b
!(a&&b) -> !a || !b
a == True -> a
a == False -> !a
1*a -> a
```

Add boolean simplifications

---

docs/utilities.rst
manticore/__main__.py
manticore/utils/log.py
tests/conftest.py

This allows projects to have more control over how Manticore logs are
handled. However, this also means that you need to explicitly enable
logging in Manticore scripts to see the logs. See
`manticore/__main__.py` file changes in this commit.

Rework logging setup

---

docs/verifier.rst

When manticore is invoked with `--contract_name CONTRACT_NAME` there is an error.
```
manticore: error: unrecognized arguments: --contract_name ERC721Final
```
The correct flag is `--contract`.

Fixed typo in verifier.rst
