- manticore/models/linux.py
See https://github.com/trailofbits/manticore/blob/master/manticore/core/smtlib/constraints.py#L202
> Fix wrong variable name in SymbolicFile

- manticore/core/cpu/abstractcpu.py
- manticore/core/executor.py
- tests/test_unicorn.py
This will let hooks access the `cpu.instruction` property
> Decode instruction early

- manticore/utils/emulate.py
Addresses the issue with non debug musl ld.so mentioned in   #221  https://github.com/trailofbits/manticore/issues/221#issuecomment-298928100
> Add hack for Unicorn YMM registers

- examples/linux/binaries/concrete_solve.py
- examples/linux/binaries/symbolic_solve.py
- examples/script/count_instructions.py
- examples/script/google2016_unbreakable/win.py
- manticore/__main__.py
- manticore/manticore.py
> Update parallel processing api

- manticore/manticore.py
- manticore/platforms/linux.py
- tests/test_unicorn.py
> Rm unused Slinux ctor params

- manticore/core/state.py
> remove default nsolves parameter from solve_n

- manticore/core/cpu/x86.py
- manticore/core/executor.py
- manticore/platforms/linux.py
- tests/auto/make_tests.py
- tests/test_slam_regre.py
Fixes issue 181.  
https://github.com/trailofbits/manticore/issues/181
> Fix x86.PUNPCKL emulation

- docs/api.rst
- manticore/__init__.py
- manticore/core/cpu/abstractcpu.py
- manticore/core/state.py
- manticore/models.py
- manticore/platforms/platform.py
- tests/test_abi.py
- tests/test_models.py
> Implement user variadic model interface

- manticore/core/cpu/arm.py
> Remove obsolete ABI code

- tests/test_manticore.py
> Unskip basic stdin test

- manticore/platforms/linux.py
Dropped SymbolicFile methods that don't do anything.
There should be test to exercise this functionality
> make SymbolicFile inherit from File

- manticore/core/executor.py
- manticore/utils/helpers.py
- scripts/benchmark.py
This should make benchmarking scripts easier, as we can just call this method from inside the script
> Move pretty printing into helpers

- manticore/core/executor.py
> rename getState to get_state

- manticore/core/executor.py
Reverts trailofbits/manticore#338
> Revert "rename getState to get_state"

- manticore/platforms/linux.py
> Fix simple abspath bug

- README.md
Now that we're doing monthly releases and making master semi-stable, let's advise users to pull from pypi.
> Update README.md to use pypi

- manticore/core/cpu/arm.py
- tests/test_armv7cpu.py
> Add ldrd and strd instructions and tests

- manticore/core/cpu/abstractcpu.py
- manticore/core/executor.py
- manticore/platforms/linux.py
> Adjust verbosity settings

- manticore/core/cpu/x86.py
> Fix capstone MOV issue

- manticore/core/executor.py
> Stop double-logging error traces

- manticore/__main__.py
- manticore/manticore.py
> Fix script verbosity

- manticore/platforms/linux.py
Should help #379 stop crashing
> Check for negative fds in fstat

- manticore/platforms/evm.py
Bugs in opcodes (too many arguments + wrong LOG name)
Fix wrong call parameters + typo
> Fix small bugs in evm 

- docs/api.rst
- docs/index.rst
- docs/models.rst
- manticore/core/state.py
> Add basic documentation on function modeling

- tests/test_memdumps.py
Should make our build stop failing
> Create workspace before running manticore to make memdump tests pass

- manticore/core/workspace.py
Should fix use cases like https://github.com/trailofbits/manticore/blob/master/manticore/manticore.py#L623
> Make save_stream pass through kwargs

- README.md
- setup.py
> Add optional redis dependency to setup.py

- manticore/__main__.py
- manticore/manticore.py
> Make makeDecree conform to convention and fix --data

- manticore/core/memory.py
- manticore/core/state.py
Fixes #406, but uses a deferred circular import to do so
> Fix forking state from memory

- manticore/core/cpu/abstractcpu.py
- manticore/core/smtlib/expression.py
- manticore/core/state.py
- tests/test_models.py
- tests/test_state.py
replace __reduce__ by  collaborative __set/getstate__
> Fix context serialization

- manticore/core/workspace.py
- manticore/manticore.py
> Log testcase generation

- docs/gotchas.rst
- docs/index.rst
> Add gotchas docs

- docs/api.rst
- manticore/manticore.py
> Document `Manticore.locked_context` API

- docs/gotchas.rst
- manticore/core/executor.py
> Seed random on policy init to make results deterministic

- manticore/core/executor.py
- manticore/manticore.py
This should make setting policy or adding callbacks much easier
> Initialize executor at manticore initialization

- manticore/manticore.py
This allows initialization of `Manticore` objects with a `State` object instead of just a path to a binary
> Allow Manticore initialization with State object

- manticore/core/workspace.py
> Concretize stdout in state summary

- README.md
- manticore/__main__.py
- manticore/manticore.py
Add more cli documentation so people don't run into issues like #464 
Fixes #472
> Document cli better

- tests/test_workspace.py
Fixes some inane code in test_output due to variable shadowing.
> Fix mistake in test_output

- manticore/core/workspace.py
- tests/test_workspace.py
> Fix stderr file creation and test for it going forwards

- Dockerfile
> Install z3 with pip in Dockerfile

- manticore/core/cpu/abstractcpu.py
- manticore/core/cpu/arm.py
- manticore/core/cpu/binja.py
- manticore/core/cpu/x86.py
- manticore/core/executor.py
- manticore/core/memory.py
- manticore/core/smtlib/__init__.py
- manticore/core/smtlib/constraints.py
- manticore/core/smtlib/solver.py
- manticore/core/smtlib/visitors.py
- manticore/core/state.py
- manticore/core/workspace.py
- manticore/manticore.py
- manticore/platforms/decree.py
- manticore/platforms/linux.py
- manticore/platforms/windows.py
- manticore/utils/emulate.py
- manticore/utils/log.py
> Pythonic logger naming

- examples/evm/reentrancy_symbolic.py
- examples/evm/seth.py
- manticore/core/workspace.py
- manticore/manticore.py
- manticore/platforms/evm.py
Fixes first part of https://github.com/trailofbits/manticore/issues/527
Swarm hash in bytecode was misinterpreted as INVALID opcode.
> Fix coverage calculation vs. metadata

- manticore/core/cpu/abstractcpu.py
- manticore/core/state.py
- manticore/platforms/linux.py
- manticore/platforms/platform.py
- tests/test_linux.py
This should fix #503, fix #515, fix #272, fix #147, and fix #509.
> Various bug fixes.

- manticore/core/smtlib/expression.py
- manticore/core/smtlib/operators.py
- manticore/utils/log.py
- scripts/stats.py
> Fix all integral type checks that forget long

- .travis.yml
> Updates travis cache to python 2.7.13

- README.md
> Updating README with solc binary requirements

- manticore/platforms/platform.py
Removed the _path variable from Platform class.
> Fixed Issue #533

- manticore/platforms/decree.py
> Fixed missing Deadlock exception in decree platform using a local definition

- manticore/seth.py
- if no logs just print nothing
- output any printable bytes in the memlog as a convenience in case they logged strings
> Refactor evm logs files content

- manticore/__main__.py
- manticore/core/plugin.py
- manticore/manticore.py
- manticore/seth.py
- manticore/utils/log.py
> EVM logging cleanup

- manticore/seth.py
We used to crash with a ValueError or KeyError if you gave a bad or empty solidity file to `ManticoreEVM.compile`. Now we raise Exceptions with an appropriate message. Open to feedback on a better exception to raise
> Add error handling to solc wrapper

- README.md
- manticore/seth.py
> 0.1.6-related cleanups

- CHANGELOG.md
- README.md
- manticore/__main__.py
- setup.py
- Updates changelog
- updates readme
- Bumps version numbers
> Manticore 0.1.6

- setup.py
> Trick rtd into thinking we don't need z3

- manticore/ethereum.py
Fixes https://github.com/trailofbits/manticore/issues/678
> Adds support for unmarshaling bytes32 type

- manticore/ethereum.py
Small bug got leaked to master
> Fix broken method declaration

- manticore/platforms/evm.py
- tests/EVM/test_EVMBLOCKHASH.py
Populates current implementation of the block header.
Fixes https://github.com/trailofbits/manticore/issues/676
Research needed.
> Quick evm header fix

- manticore/ethereum.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/697)
> Added multiprocessing support to generate testcases in finalize

- manticore/ethereum.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/733)
> Small cleanups for dynarg PR

- manticore/platforms/evm.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/745)
> Fixed Issue #723 - changed _pop() to _pop_vm()

- manticore/platforms/evm.py
Some examples failed when gas too low. 
Better higher gas budget so user is not annoyed with it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/740)
> Bump default gas budget

- docs/api.rst
- docs/gotchas.rst
- docs/index.rst
- docs/syminput.rst
Fixes #747 
looks like this:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/750)
> Add docs on symbolic input

- examples/evm/use_def.py
- manticore/__main__.py
- manticore/core/plugin.py
- manticore/ethereum.py
- manticore/manticore.py
- manticore/platforms/evm.py
Internal, vs external transactions.
Example UseDef logging plugin for evm.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/730)
> Better plugin context management.

- manticore/core/cpu/arm.py
- tests/test_armv7cpu.py
- tests/test_unicorn.py
Removes dead imports, makes code style more consistent and a bit more compliant with pep8 (yeah i seems we don't enforce any particular style, but this seems to be a reasonable default for me).
...lets see if it passes CI checks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/749)
> Armv7 code refactor

- manticore/core/smtlib/visitors.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/762)
> Drive-by typo correction ;-)

- tests/binaries/676.sol
- tests/binaries/678.sol
- tests/binaries/701.sol
- tests/binaries/705.sol
- tests/binaries/714.sol
- tests/binaries/735.sol
- tests/binaries/760.sol
- tests/binaries/imp.sol
- tests/test_binaries.py
Add tests for various simple contracts 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/763)
> Add ethereum regression tests

- manticore/ethereum.py
When solc has an error we used to just say that. Now we also print the solc error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/765)
> Improve solc error output

- manticore/ethereum.py
- tests/test_eth.py
This implements a (more) correct MUL overflow detector.
Fixes #714
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/767)
> evm: Fix MUL overflow false positive

- manticore/core/cpu/abstractcpu.py
When particular instruction's implementation raised an `AttributeError` it was catched by `Cpu.execute` and we just saw "oh this instruction is not implemented" while it was, but its implementation was broken.
(Found that when playing with adding `MOV` for aarch64 :P)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/777)
> Fix Cpu.execute's improper reporting of `Unimplemented instruction`

- manticore/utils/emulate.py
This probably also speeds up a bit execution when we use emulation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/779)
> Unicorn emulator: get uc_arch & uc_mode values just once

- manticore/platforms/evm.py
Imported namedtuple from collections
Created a namedtuple PendingTransaction which is assigned to self._pending_transcation
Fixes #689
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/775)
> Used a namedtuple for pending transaction. Issue #689

- manticore/__main__.py
- manticore/manticore.py
This allows a user to specify initial concrete data for stdin. Previously it was just ignored, this PR reactivates it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/781)
> Fix cli --data parameter

- manticore/core/cpu/arm.py
So that people don't have to google this by themselves! lolo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/788)
> Add docstring for ARM's operand.is_shifted

- manticore/ethereum.py
Possible fix for #782
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/791)
> Added a function to generate evm testcases without using callbacks

- manticore/ethereum.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/794)
> Very quick fix for #792 based on PR #793

- manticore/platforms/evm.py
- tests/test_eth.py
Standardize on the way `Create` is created and used.
Fixes #799.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/805)
> Update Create (evm exception) arguments

- docs/api.rst
- manticore/ethereum.py
Add docstr for ManticorEVM.finalize()
Prune unrelated docs.
Fixes #790
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/816)
> Improve evm docs

- manticore/platforms/evm.py
Quickfix for https://github.com/trailofbits/manticore/issues/829
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/830)
> Push 0 on internal revert

- examples/evm/complete.py
This example is more suitable for the blockchain tool blog post.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/827)
> A more complete example to initialize and explore a smart contract with manticore

- CHANGELOG.md
- manticore/__main__.py
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/851)
> Manticore 0.1.8

- tests/auto/trace.py
#823 On a diet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/854)
> Do not forget self (again)

- .codeclimate.yml
- manticore/core/memory.py
- manticore/core/smtlib/constraints.py
- manticore/core/smtlib/expression.py
- manticore/core/smtlib/solver.py
- manticore/core/smtlib/visitors.py
- manticore/core/state.py
- manticore/ethereum.py
- manticore/platforms/evm.py
- tests/test_eth.py
- tests/test_models.py
- tests/test_smtlibv2.py
This PR contains most of the various fixes and improvements from #715 without some of the more controversial/unfinished code related to dynamic argument concretization.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/855)
> Ethereum ABI and misc fixes

- manticore/core/smtlib/solver.py
This removes some code that was doing a lot of unnecessary, expensive solver resetting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/859)
> Speed up solver get_all_values

- manticore/__main__.py
- manticore/ethereum.py
This new option allows manticore to explore the execution of contracts it finds no more live state or reaches the txlimit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/849)
> Added --txnocoverage option to manticore cli

- manticore/ethereum.py
Fixes 
https://github.com/trailofbits/manticore/issues/846
https://github.com/trailofbits/manticore/issues/844
Creates the need for
https://github.com/trailofbits/manticore/issues/847
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/848)
> Fix check of solc metadata tail

- manticore/core/cpu/x86.py
- tests/test_cpu_manual.py
Fixes #560
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/852)
> Sign extends x86 AND operand (capstone bug)

- CHANGELOG.md
- manticore/__main__.py
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/888)
> Manticore 0.1.9

- manticore/core/memory.py
- manticore/utils/mappings.py
With these changes, I am able to run Manticore on Linux (static)
binaries from a NetBSD host.
Tested with NetBSD/amd64 (7.1_STABLE XEN3_DOM0).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/893)
> Add support for NetBSD as a host OS

- tests/test_eth.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/918)
> Add regression test for posCAll bug

- tests/test_eth.py
Fix eth test to use correct variable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/925)
> Fix eth internal regression test

- manticore/platforms/evm.py
Minimal doc for evm.*storage*() functions
Move world_state to _world_state so it usage is discouraged in favor of APIs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/915)
> Initial doc to storage evm functions

- manticore/core/smtlib/expression.py
Fix #932
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/934)
> Fix Taint on Ct Eq

- manticore/core/smtlib/operators.py
- manticore/platforms/evm.py
Fix #930
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/933)
> Fix  evm SDIV/SMOD

- manticore/core/smtlib/constraints.py
__str__ implemented via to_string in constraintSet
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/942)
> Remove dead code

- manticore/ethereum.py
- manticore/platforms/evm.py
- tests/test_eth.py
Mini refactor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/938)
> Change EVMAsm offset by pc

- CHANGELOG.md
- manticore/__main__.py
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/941)
> Manticore 0.1.10

- manticore/core/workspace.py
- tests/test_linux.py
- tests/test_manticore.py
- remove dead code in workspace.py
- add test for symbolic argv/envp in linux
- add test for @m.init
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/956)
> Add some unit tests, rm dead code

- manticore/core/smtlib/expression.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/971)
> Fix slicing wrongly reference to proxyArray. Fix #912

- manticore/ethereum.py
re #912
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/972)
> Only export human/external tx in the testcase

- manticore/ethereum.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/974)
> Make ManticoreEVM.make_symbolic_value size adjustable

- manticore/__main__.py
- manticore/ethereum.py
- manticore/platforms/evm.py
- tests/binaries/benchmark/eth_tx_order_dependence_multitx_1.sol
- tests/eth_benchmark.py
Fix gas usage in CALL
Fix gas check in DAO check
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/975)
> Dev evm yolo fix gas

- manticore/core/smtlib/constraints.py
- manticore/core/smtlib/expression.py
- manticore/core/smtlib/visitors.py
- manticore/ethereum.py
- manticore/platforms/evm.py
- tests/eth_general.py
Several typo-like bugfixes in expressions/visitors/migration
New simplification
Fixes #950. SDIV correctness fix. :( :( :( Need thorough test suit for instructions!!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/985)
> Sveral expression/migration/visitors bugfixes. Fix 950

- manticore/ethereum.py
- tests/test_binaries.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1011)
> re-enable and fix eth regression 808

- manticore/platforms/linux.py
Fixes trailofbits/manticore#954
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/955)
> Add uncaught exception

- setup.py
So that we can, for instance, have raspberry hello world running (see #514)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1026)
> Use capstone 3.0.5 and no longer rc2

- manticore/core/smtlib/visitors.py
- manticore/utils/helpers.py
* reimplement caching for `arithmetic_simplifier` and `constant_folder`
* optimize `ArithmeticSimplifier.visit_ArraySelect`
re; #1016
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1017)
> Addresses performance issues;

- manticore/platforms/linux.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1019)
> File mode fix - resolves #1018

- Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1030)
> fixes docker - resolves #991

- manticore/__main__.py
- manticore/manticore.py
- manticore/platforms/linux.py
- manticore/utils/helpers.py
dead feature/code cleanup
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1028)
> binja cleanup

- manticore/core/smtlib/solver.py
- manticore/ethereum.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1033)
> resolves #992

- README.md
https://github.com/trailofbits/manticore/issues/1003
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1034)
> readme Ethereum update issue #1003

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1038)
> Ignore resource warnings (e.g. unclosed files)

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1041)
> Emphasize new python requirement

- examples/evm/use_def.py
- scripts/benchmark.py
- scripts/extract_syscalls.py
- scripts/follow_trace.py
- scripts/gdb.py
- scripts/stats.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1042)
> Port remaining examples to py3

- manticore/manticore.py
- tests/test_manticore.py
- resolves #982
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1057)
> Fix missing profiling data

- manticore/ethereum.py
- tests/eth_general.py
This is a very quick fix for the invalid printing of arguments in a function call.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1063)
> Fix for #1008

- manticore/ethereum.py
- tests/eth_benchmark.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1073)
> Fix typo mistake in multi-million word

- manticore/__main__.py
- manticore/ethereum.py
- tests/eth_detectors.py
Modify the etherleak detector also add findings for general user controlled external call situations.
fixes #1056 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1087)
> Add detector for plain external call

- manticore/ethereum.py
- manticore/platforms/evm.py
- tests/binaries/detectors/predictable_not_ok.sol
- tests/eth_detectors.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1096)
> Detection of environmental and potentially manipulable instruction/data

- manticore/__main__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1105)
> Add env instruction detector to cli

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1109)
> Updates to README.md relating to Python 3 migration and sudo within virtualenv setup

- CHANGELOG.md
- LICENSE
- README.md
- manticore/__main__.py
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1106)
> Manticore 0.2.1

- CHANGELOG.md
- manticore/__main__.py
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1111)
> Release 0.2.1c

- CHANGELOG.md
- manticore/__main__.py
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1112)
> Fix the versioning hell

- CHANGELOG.md
- manticore/__main__.py
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1113)
> Fix version number / release

- CHANGELOG.md
- manticore/__main__.py
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1114)
> Manticore 0.2.1-berlin

- CHANGELOG.md
- manticore/__main__.py
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1115)
> Manticore 0.2.1-b

- CHANGELOG.md
- manticore/__main__.py
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1116)
> manticore 0.2.1.1

- manticore/platforms/evm.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1118)
> Changed instances of Concretice to Concretize

- manticore/ethereum.py
Due to the issues described in #1123.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1124)
> Don't recommend snap solc install in README

- manticore/__main__.py
Helping with #1104
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1129)
> Fix typos in help

- README.md
it should be uniform with rattle and slither
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1131)
> license phrasing uniformity

- manticore/__main__.py
Fix commandline access so DetectReentrancyAdvanced is accessible
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1132)
> DetectReentrancyAdvanced from cli

- README.md
> Rm obsolete asciinema

- manticore/core/executor.py
- manticore/core/smtlib/solver.py
- manticore/ethereum/__init__.py
- manticore/exceptions.py
- manticore/manticore.py
- manticore/platforms/linux.py
> raise error instead of silently fail

- manticore/ethereum/detectors.py
also check if dest can solve to > 1
#1077 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1153)
> small ethleak improvement

- manticore/ethereum/__init__.py
Relocate the really big internal sections
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1155)
> Refactor _generate_testcase_callback

- manticore/ethereum/__init__.py
Fix https://github.com/trailofbits/manticore/issues/1175
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1176)
> Fix symbolic sha3

- manticore/platforms/evm.py
- tests/eth_general.py
Addresses Consensus errors #1169.3
This is an initial consensus phase. Todo: incorporate official tx related xml tests. 
```
DELEGATECALL/CALLCODE quirks. It looks like DELEGATECALL passes the current address as sender here. That's how CALLCODE works, whereas DELEGATECALL should pass the original sender as sender.
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1179)
> Add specific ad-hoc delegatecall test and fix

- manticore/ethereum/__init__.py
- manticore/platforms/evm.py
- tests/eth_general.py
Change list to sets for selfdestructed contracts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1180)
> Change selfdestruct list to a set to avoid dups

- manticore/__main__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1183)
> Fix detect reentrancy adv. cli

- manticore/ethereum/abi.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1190)
> Fix logic in eth abi

- manticore/core/smtlib/solver.py
Small fix, going to merge if tests pass.
> Properly split z3 command

- manticore/ethereum/__init__.py
- tests/eth_general.py
This invalidates #1214.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1221)
> Add convenience assertion & generate API

- manticore/core/state.py
- manticore/ethereum/__init__.py
Fixes https://github.com/trailofbits/manticore/issues/1103.
_(BTW, this is Alan, the new intern)_
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1222)
> Add AbandonState exception

- manticore/core/state.py
- manticore/ethereum/__init__.py
Reverts trailofbits/manticore#1222
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1225)
> Revert "Add AbandonState exception"

- manticore/core/state.py
- manticore/ethereum/__init__.py
@stephan-tolksdorf @disconnect3d 
Added the changes. Is there anything I might need to do with the test cases in order for the executor to raise exceptions?
Thanks for the help!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1226)
> Add AbandonState Exception (Fixes #1222)

- manticore/ethereum/__init__.py
- manticore/ethereum/abi.py
- manticore/manticore.py
- manticore/platforms/evm.py
Use more specific, standard errors in some places.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1218)
> Improve exceptions and errors

- manticore/ethereum/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1228)
> don't show misleading msg if state count is 0

- CHANGELOG.md
- manticore/__main__.py
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1229)
> Manticore 0.2.2

- manticore/core/cpu/abstractcpu.py
As requested in https://github.com/trailofbits/manticore/commit/e1b6f1a5bd21eb7077bcf3edc48b76b40b201522#r31119722.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1232)
> Fix missing % operator

- manticore/ethereum/account.py
Fix https://github.com/trailofbits/manticore/issues/1234
Forgiving default added
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1235)
> Let EVMAccount control the gas of the transaction. 

- manticore/__main__.py
- manticore/manticore.py
- tests/test_binaries.py
Fixes https://github.com/trailofbits/manticore/issues/1130
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1186)
> added timeout support for ManticoreEVM

- manticore/ethereum/__init__.py
The error was introduced in commit e18016a.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1238)
> Fix type check for caller arg in ManticoreEVM._transaction

- manticore/platforms/evm.py
- tests/eth_general.py
Fixes issue #1255.
Also adds type hints to some private attributes of the EVMWorld class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1256)
> Fix event forwarding after state fork in EVM message call

- manticore/platforms/evm.py
- tests/eth_detectors.py
- tests/eth_general.py
Fixes issue #1237.
I will fix the `DetectExternalCallAndLeak` tests later and, if still necessary, add a test for the previously buggy behaviour.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1246)
> Fix exception handling in EVM.transact._pre_func

- manticore/core/smtlib/expression.py
- manticore/core/smtlib/visitors.py
- manticore/core/state.py
- tests/test_memory.py
- tests/test_smtlibv2.py
- tests/test_state.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1261)
> New simplification with tests and new state.solve_minmax aux fuc

- manticore/ethereum/__init__.py
- tests/eth_general.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1267)
> Change generate_testcase name to have a default val

- README.md
We don't need to clone Manticore repo or mount examples into the container as those are already inside the container.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1266)
> Fix Docker instructions

- manticore/core/smtlib/visitors.py
- tests/test_smtlibv2.py
Bitvecconcat needs `size` not `end`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1275)
> BitvecConcat simplification fix

- manticore/core/smtlib/operators.py
The else condition can never be fulfilled as it is the same as the one inside the if statement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1280)
> Incorrect branching based on instance type

- manticore/core/state.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1282)
> Add not implemented stub for execute() in state parent

- manticore/utils/emulate.py
Fixes #1287
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1290)
> Remove unnecessary unicorn hack

- manticore/core/executor.py
- manticore/core/smtlib/solver.py
- manticore/exceptions.py
- manticore/platforms/linux.py
As in the TODO.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1288)
> Rename SolverException to SolverError

- manticore/core/smtlib/constraints.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1293)
> More explicit smt errors

- manticore/ethereum/cli.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1299)
> Disable RaceCondition detector

- CHANGELOG.md
- Dockerfile
- README.md
- manticore/__main__.py
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1298)
> Manticore 0.2.3

- tests/test_manticore.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1308)
> test_manticore: remove redundant imports

- manticore/core/manticore.py
- manticore/native/manticore.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1309)
> Migrate hook callback methods to native.Manticore

- manticore/ethereum/manticore.py
- tests/eth_general.py
Fixes #1325
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1326)
> Fix terminated states resurrection

- CHANGELOG.md
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1338)
> Manticore 0.2.4

- manticore/utils/config.py
As in commits:
* Optimized imports with PyCharm
* Use dict literal instead of dict() - not really necessary at all, but dict literal is faster lol
* config.py: process_config_values move type info to type adnotations
* Renamed `_Group` -> `Group`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1335)
> Refactor config

- manticore/ethereum/manticore.py
- manticore/platforms/evm.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1346)
> Move tx default gas value to config

- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1312)
> Update Capstone to 4.0.1

- manticore/utils/config.py
- tests/test_config.py
This changes introduces possibility to make temporary changes to config groups.
See tests for an example ;).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1345)
> Config with context

- docs/gotchas.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1360)
> Fix a typo in the documentation

- manticore/platforms/evm.py
The `get_possible_solutions` was an internal function used just once and it was recreated each
time the `_consume` was executed. This PR removes/inlines this function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1372)
> Inline EVM's get_possible_solutions

- Dockerfile
- examples/linux/crackme.py
This is just the result of running `black` on `crackme.py`, plus a change to ~~how the program is emitted to circumvent some locale dumbness in the Docker image~~ the Dockerfile to set the correct locale.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1378)
> examples/linux: Refactor, fix crackme.py

- manticore/ethereum/manticore.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1386)
> Better doc for solc fails

- CHANGELOG.md
- setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1390)
> Release 0.2.5

- manticore/utils/event.py
Performance optimization
CC @artemdinaburg @ehennenfent
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1388)
> Only publish events when there is one subscriber

- manticore/ethereum/detectors.py
Resolves issue #1394.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1395)
> Concretize `pc` if possible when adding Ethereum detector findings

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1397)
> Fixed Empire Hacking invitation link

- examples/script/concolic.py
- manticore/ethereum/manticore.py
- manticore/platforms/evm.py
- tests/auto_generators/make_tests.py
- tests/ethereum/test_general.py
- tests/native/test_armv7cpu.py
- tests/native/test_unicorn.py
They were making it hard to implement hard timeouts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1405)
> Remove all broad excepts

- scripts/sandshrew.py
- scripts/sandshrew/README.md
- scripts/sandshrew/TUTORIAL.md
- scripts/sandshrew/WRITING_TEST_CASES.md
- scripts/sandshrew/examples/Makefile
- scripts/sandshrew/examples/test_openssl_bnsqr.c
- scripts/sandshrew/examples/test_openssl_md5.c
- scripts/sandshrew/examples/test_tweetnacl_scalarmult.c
- scripts/sandshrew/sandshrew.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1396)
> Migrate sandshrew concolic executor as Manticore script

- manticore/platforms/decree.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1413)
> Fix DECREE Magic Pages

- manticore/core/manticore.py
- manticore/platforms/linux.py
Based on description from http://man7.org/linux/man-pages/man2/getdents.2.html and tested on example within that document.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1472)
> Fix sycall getdents

- manticore/core/manticore.py
- manticore/ethereum/manticore.py
Resolves #1475. Someone should double-check the deprecation warning messages I added to ensure that they provide the correct recommendations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1476)
> Improve deprecation warnings

- manticore/native/memory.py
- tests/native/test_memory.py
Improves SMemory tests and adds more docs to it.
This is going to help debug, fix and either merge or close #1465.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trailofbits/manticore/1506)
> Improve smemory tests

- manticore/utils/emulate.py
- manticore/utils/fallback_emulator.py
- scripts/travis_install.sh
- setup.py
- tests/native/test_unicorn_concrete.py
Unicorn still doesn't like writing to the `FS` register.
closes #1434
> Update Unicorn to 1.0.2rc1

- .travis.yml
- manticore/platforms/linux.py
- tests/native/test_syscalls.py
**Changes:**
* Passing argument just as @ehennenfent  explained
* Alter the test from expect failure to succeed
Let me know if this would need more work.
> fixes #1521 - add avoid_collision argument and alter test

- manticore/ethereum/manticore.py
Change/fix  default in --help doc for --sha3 type.
> fix --help doc sha3 default

- manticore/core/smtlib/solver.py
- tests/other/test_smtlibv2.py
* Fix for long format Z3 version with git hash
* Fix for unparsable Z3 version to assume newer and compatible
> Fix Z3 version parsing

- manticore/core/smtlib/expression.py
> Arrayvarname

- manticore/core/smtlib/expression.py
- manticore/native/cpu/abstractcpu.py
- manticore/platforms/evm.py
like #1552 
Are you planning on using it ?
> Fixes different problems found by lgtm

- scripts/travis_install.sh
- scripts/travis_test.sh
- setup.py
This may not help much yet, but let's see what CI has to say.
> try pytest xdist

- examples/script/concolic.py
> Fix deprecation warnings related to setting verbosity

- .github/workflows/ci.yml
- mypy.ini
Use explicit file path in mypy.ini for default runs
> Run mypy on manticore directory by default

- .gitignore
> Add .mypy_cache to .gitignore.

- .github/workflows/ci.yml
> Fix minor indentation issue in ci.yml.

- README.md
> Add Examples badge to CI Badges

- manticore/platforms/linux.py
@bradlarsen Check if this works please
closes #1602
> Make sure std files are not None before assigning peer

- .github/workflows/ci.yml
- manticore/ethereum/cli.py
- manticore/ethereum/manticore.py
- manticore/platforms/evm.py
- tests/ethereum/test_general.py
Add a config constant to enable exploration with symbolic balances
> Improve balance related exploration

- manticore/ethereum/manticore.py
Sorry, this has been driving me nuts.
> Typo: "insteance"

- manticore/ethereum/manticore.py
Transaction gas related argument renamed to more representative name
> Better argument names in manticoreEVM api

- tests/wasm/generate_tests.sh
- tests/wasm_sym/generate_symbolic_tests.sh
> Change URL for WASM spec

- manticore/core/worker.py
- manticore/utils/log.py
Two minor commits meant to reduce log noise.
> Reduce log messages

- .github/workflows/ci.yml
https://coveralls-python.readthedocs.io/en/latest/usage/configuration.html#github-actions-gotcha
> Fix Coveralls for external PRs

- manticore/native/manticore.py
> Fix state.cpu.PC member

- .github/workflows/ci.yml
New version broke us.
Reference: https://github.com/coveralls-clients/coveralls-python/issues/251
> Fix coveralls upload

- manticore/core/smtlib/solver.py
Added missing timeout options for cvc4 and boolector
> Added proper timeouts for cvc4 and boolector

- scripts/run_tests.sh
Quick fix for the recent change in the repository containing the EVM tests
> Fix the generation of EVM tests

- manticore/ethereum/manticore.py
- setup.py
See https://github.com/crytic/crytic-compile/pull/167
The changes in `setup.py` are temporary and will be removed before the next release
> Add support for multiple compilation units

- manticore/native/cpu/aarch64.py
- manticore/native/cpu/abstractcpu.py
- manticore/native/cpu/arm.py
- manticore/native/cpu/x86.py
- manticore/native/state.py
- manticore/platforms/linux.py
These features were added for development on the heap tracking module contained in the chess branch.
Related to #2469
> Get Result Register

- manticore/native/cpu/abstractcpu.py
This is useful if you have multiple plugins and don't want them to
capture memory reads that are executed by other plugins.
Removed some type hints in the comments because they caused cascading
errors, and fixing those cascading errors should be a part of another
PR.
> Optionally publish events for memory reads

- manticore/core/smtlib/solver.py
Helps with debugging if/when things go bad during solving
> Add more logging messages around solver errors

- manticore/native/cpu/aarch64.py
- manticore/native/cpu/abstractcpu.py
- manticore/native/cpu/arm.py
- manticore/native/cpu/register.py
- manticore/native/cpu/x86.py
- tests/native/test_aarch64cpu.py
- tests/native/test_armv7cpu.py
- tests/native/test_register.py
- tests/native/test_x86.py
Would appreciate a sanity check on the tests!
> Snapshot a RegisterFile

- setup.py
> Enforce crytic-compile==0.2.1

- .github/workflows/pip-audit.yml
Replaces the manual use here with our official GitHub Action.
Signed-off-by: William Woodruff <william@trailofbits.com>
> workflows/pip-audit: use our official action

- .github/workflows/ci.yml
> Retry coveralls upload

- .github/workflows/ci.yml
- .github/workflows/release.yml
- Dockerfile
- examples/linux/ioctl_bogus.c
- examples/linux/ioctl_socket.c
Ubuntu 18.04 runners are deprecated
> Use Ubuntu 20.04 in CI

- .github/workflows/pip-audit.yml
Signed-off-by: William Woodruff <william@trailofbits.com>
> workflows/pip-audit: change gh-action-pip-audit slug to pypa

- .github/workflows/pip-audit.yml
- server/setup.py
Protobuf types version should match version of protobuf library
> Constrain protobuf types to 3.20

- README.md
cf. https://github.com/badges/shields/issues/8671
> [chore] fix build badges

- README.md
- docs/verifier.rst
> Fix: typos
